### ISSUE TITLE
IXA pipes hackathon

### ISSUE THREAD

**Issue by ragerri** [openminted/Open-Call-Discussions#28] opened 2018-04-12 16:15 UTC
Mostly I would like to know how to ensure that our component actually works for OMTD. I have shared a component as docker and before I upload the rest of the components I would like to make sure that I am doing things correctly.

Thanks

R

**Comment by galanisd** [comment] 2018-04-12 22:06
Hi,

It seems that you have registered IXA several times.
https://test.openminted.eu/search;query=IXA
Correct?

Which is the latest version? This one?
https://test.openminted.eu/landingPage/component/d2d4a389-f243-4378-b0a3-90cf91b8209f ?

**Comment by ragerri** [comment] 2018-04-13 07:24
Hello,

Yes, the last one.

Cheers,

R

**Comment by galanisd** [comment] 2018-04-13 08:59
I will delete the old versions and have a look to the latest.

**Comment by galanisd** [comment] 2018-04-13 10:23
* Deleted and kept only https://test.openminted.eu/landingPage/component/d2d4a389-f243-4378-b0a3-90cf91b8209f
* running some "docker run" tests outside Galaxy
* running some tests with Galaxy @ OMTD with a  test workflow.

Please can you send me some sample input files for you component just to be sure.

**Comment by ragerri** [comment] 2018-04-13 10:33
Hello,

Sure, here it is one.

https://raw.githubusercontent.com/ragerri/ixa-pipes-omtd/master/en/input.xmi

R

**Comment by galanisd** [comment] 2018-04-13 16:19
* Local "docker run"  test has succeeded with the file that you provided. Attached the output.
[IXAOUT.zip](https://github.com/openminted/Open-Call-Discussions/files/1908041/IXAOUT.zip).
Please can you have a look and confirm that it is OK?

*  Galaxy test @ OMTD has not succeeded. I get the following message.
ERROR: --output must be a directory

I had a look into en-ixa-pipes.sh (your executor) ...got it from your image. It seems OK.
I do not understand why it does not work; probably it has to do with the code that Galaxy uses to
call your executor. 

Is it possible to copy the executor (en-ixa-pipes.sh) in /usr/bin/ and provide an updated image?
I have successfully tested images with this structure in the past. 
e.g. https://github.com/openminted/omtd-component-executor/blob/master/omtd-component-executor-gate.dockerfile

Then I will be able to call the executor by  just running en-ixa-pipes.sh OR bash en-ixa-pipes.sh. 

Thanks

Dimitris

**Comment by galanisd** [comment] 2018-04-13 17:02
Also, I just noticed that in some executors that I have created or contributed ...the output directory is created by the executor if it does not exist.  E.g. https://github.com/openminted/omtd-component-executor/blob/master/omtd-component-webservice/src/main/java/eu/openminted/component/webservice/WebServiceClient.java

Maybe Galaxy tries to create it and fails. It might has to do with the configuration/setup of Galaxy + Docker. This explains why we get a "ERROR: --output must be a directory" message. The directory does not exist. 

Please can you take care of this in the script (executor) and provide an updated image.

Thanks

**Comment by greenwoodma** [comment] 2018-04-16 12:24
To make sure we are as well prepared as possible to help during the hackathon sessions could you please add/attach to this issue:

1. The landing page URL of any component/workflow you have registered
2. The OMTD-SHARE XML file for each component/workflow
3. One or two sample documents that you expect to produce sensible output for your component/workflow

**Comment by ragerri** [comment] 2018-04-16 14:09
Hello Dimitrios,

Thanks for your help. I have made the changes you suggested and the local
tests work fine (e.g., it creates the output dir if it does not exists).
Here it is the new version of the component:

https://test.openminted.eu/landingPage/component/6ab57399-1f12-4c9d-9038-c9550db29956

Let's see if that works now in the Galaxy test @ OMTD.

Cheers,

Rodrigo

On Fri, Apr 13, 2018 at 7:02 PM, Dimitrios Galanis <notifications@github.com

**Comment by ragerri** [comment] 2018-04-16 14:23
Hello Mark.

1. Landing Page:
https://test.openminted.eu/landingPage/component/6ab57399-1f12-4c9d-9038-c9550db29956
2. Descriptor attached.
3. Two input files attached.

Best regards,

Rodrigo


On Mon, Apr 16, 2018 at 2:24 PM, Mark A. Greenwood <notifications@github.com

**Comment by gkirtzou** [comment] 2018-04-16 14:32
@ragerri  You have forgotten to attach the attachements

**Comment by galanisd** [comment] 2018-04-16 14:34
It seems that you provided the same image
ragerri/en-ixa-pipes-omtd:0.0.1
same version (0.0.1).  This is the correct one? Is it possible to update a tagged image in DockerHub?

Also I did a docker pull...and  says that nothing changed.

**Comment by ragerri** [comment] 2018-04-16 14:39
Attachments, I did not realize that by email are not included.

[corpus_in.tar.gz](https://github.com/openminted/Open-Call-Discussions/files/1915756/corpus_in.tar.gz)

The descriptor was not correct, so I have update it.

[en-ixa-pipes-omtd-descriptor.xml.gz](https://github.com/openminted/Open-Call-Discussions/files/1916010/en-ixa-pipes-omtd-descriptor.xml.gz)

**Comment by ragerri** [comment] 2018-04-16 14:43
Hello Dimitrios,
https://hub.docker.com/r/ragerri/en-ixa-pipes-omtd/tags/

yes, the tagged image is in the Docker Hub:

new tag: 0.1.0 -> old tag 0.0.1

docker pull ragerri/en-ixa-pipes-omtd:0.1.0

The OMTD descriptor has changed accordingly. Now I have two components. The one I uploaded to day that points to the 0.1.0 tag in docker hub and the one I uploaded last week.

Thanks

R

**Comment by galanisd** [comment] 2018-04-16 15:24
OK but in OMTD-SHARE of https://test.openminted.eu/landingPage/component/6ab57399-1f12-4c9d-9038-c9550db29956 
I see
`<ns0:distributionLocation>ragerri/en-ixa-pipes-omtd:0.0.1</ns0:distributionLocation>`
the old tag.

not 0.1.0
See also the en-ixa-pipes-omtd-descriptor.xml.gz that you provided above.

Do I miss something?

Thanks.

**Comment by ragerri** [comment] 2018-04-16 15:30
Hello,

I might have messed up with the descriptor :(

It should be correct now.

https://test.openminted.eu/landingPage/component/a448caa2-c1c3-4de1-9fda-c4657893b4be

Cheers,

R

On Mon, Apr 16, 2018 at 5:25 PM, Dimitrios Galanis <notifications@github.com

**Comment by galanisd** [comment] 2018-04-16 15:33
Now it is correct. I will delete the old versions from Registry. 

Thanks!

**Comment by galanisd** [comment] 2018-04-16 16:00
Tested failed. Again ERROR: --output must be a directory
I did this to see `en-ixa-pipes.sh` 
`docker run ragerri/en-ixa-pipes-omtd:0.1.0 /bin/bash -c "cat en-ixa-pipes.sh" | more` 

`if [ ! -d ${output} ]; then
        mkdir ${output}
        echo "ERROR: --output must be a directory"
        exit 1
fi
`
the directory is probably created but then ...exit. :-)

**Comment by ragerri** [comment] 2018-04-16 16:26
OK :)

Let's see now. Version 0.1.1

https://test.openminted.eu/landingPage/component/f06baf6a-4000-4afb-88e5-44c85b02cf11

Thanks,

R

On Mon, Apr 16, 2018 at 6:00 PM, Dimitrios Galanis <notifications@github.com

**Comment by galanisd** [comment] 2018-04-16 17:19
Problem solved...
New one...
`Creating --output directory
/en-ixa-pipes.sh: line 10: ./xmi2naf.py: No such file or directory
/en-ixa-pipes.sh: line 16: ./naf2xmi.py: No such file or directory
/en-ixa-pipes.sh: line 10: ./xmi2naf.py: No such file or directory
/en-ixa-pipes.sh: line 16: ./naf2xmi.py: No such file or directory`

I know what happens. Galaxy creates a directory "working" in the container and runs from there 
the code that was generated for calling your component.

So, xmi2naf.py is here / and can't be found. You have to make your executables (xmi2naf.py, ixa-pipe-tok-exec.jar, ...) visible/runnable from everywhere.
See more info here
https://unix.stackexchange.com/questions/3809/how-can-i-make-a-program-executable-from-everywhere

**Comment by galanisd** [comment] 2018-04-16 17:23
...
2 solutions
* Add them all to /usr/bin/
OR
* Call them in  en-ixa-pipes.sh using absolute paths as you do with en-ixa-pipes.sh.
 en-ixa-pipes.sh is called  /en-ixa-pipes.sh ...

We are pretty close

**Comment by gkirtzou** [comment] 2018-04-17 09:08
@ragerri 
As far as the metadata of your component is concerned, I would like to propose a few changes, in order to have meaningful metadata, for better visibility and usability of your component. There are not obligatory changes, but recommented. 

In the description of your component, you say "It provides tokenizer, POS tagger, lemmatizer, NER tagger, Chunking and Document Classification. ". It would be nice to add this information also to the outputResourceInfo.annotationTypes. I think the following types of annotations are generated by your component, correct?

- http://w3id.org/meta-share/omtd-share/Token
- http://w3id.org/meta-share/omtd-share/PartOfSpeech
- http://w3id.org/meta-share/omtd-share/Lemma
- http://w3id.org/meta-share/omtd-share/NamedEntity
- http://w3id.org/meta-share/omtd-share/Chunk
- http://w3id.org/meta-share/omtd-share/Topic

Also, it would be nice to add the language element in the outputResourceInfo, since you provide this information also to the inputContentResourceInfo.

**Comment by pennyl67** [comment] 2018-04-17 09:46
@ragerri 
Hi Rodrigo
A couple of additional recommendations for the metadata - and a question: how did you generate it? Straight as an XML file or through the editor? (this will help us keep track of some administrative issues)
- for the function, please use http://w3id.org/meta-share/omtd-share/Annotator as it describes better what the component does - it's not an operational issue, but a discoverability one
- could you add resourceCreationInfo with resourceCreator? It's not mandatory but it will help the citation process
- if you have any extra information material (e.g. publications, user manual etc.) on the IXA pipes, you can use the resourceDocumentationInfo for that reason
Thanks,
Penny

**Comment by ragerri** [comment] 2018-04-17 12:35
Hello Dimitrios,

I have them the changes regarding the absolute paths.

https://test.openminted.eu/landingPage/component/ff94e664-8555-4f04-bb03-1be6d225c9e1

Thanks for your help,

Rodrigo

On Mon, Apr 16, 2018 at 7:26 PM, Dimitrios Galanis <notifications@github.com

**Comment by ragerri** [comment] 2018-04-17 12:44
Dear Katerina and Penny,

Indeed it would be nice to add:

1. outputResourceInfo.annotationTypes (6 types you mentioned).
2. outputResourceInfo: language element
3. resourceCreationInfo and resourceCreator
4. Extra Information material on the IXA pipes (resourceDocumentionInfo)

The problem is that I have never managed to register a component through
the editor. I have tried today again in order to fill in those elements but
I always get the same error regarding the contactType: I get to add the
contactPoint, but I cannot choose or see the contactType (in my case,
landingPage), so the editor gives me this error. As I cannot save or see a
preview of the editor, I cannot copy those fields to the XML I manually
upload to register the component.

I can try and manually add those elements. I will do that when the
component passes the OMTD Galaxy tests.

Thanks,

Rodrigo

**Comment by pennyl67** [comment] 2018-04-17 13:48
For the metadata elements, don't worry; once you finish all the tests, and everything is ok, send me the record and I'll add them for you.
For the editor, the problem is due to the fact that it automatically considers that the person adding the metadata is also the contact person; I'll report to the implementors - thanks for noticing!

**Comment by galanisd** [comment] 2018-04-17 14:34
Succeeded...Please have a look
- Input (2XMI files)
[xmiINIXA.zip](https://github.com/openminted/Open-Call-Discussions/files/1920224/xmiINIXA.zip)
- Output
[_WF_IXAoutput_2018-04-17-17_22_48.zip](https://github.com/openminted/Open-Call-Discussions/files/1920205/_WF_IXAoutput_2018-04-17-17_22_48.zip)

The workflow was
omtdImporter -> IXA
The first step just gets the data from the OMTD Storage.

Good news :-)

I assume that if we create a workflow
omtdImporter -> PDFReader -> IXA
and provide a corpus of PDFs it will also work.

**Comment by ragerri** [comment] 2018-04-17 16:13
Hello,

Excellent. I assume that I can go on uploading the rest of my components to
following this structure, right?

Best,

Rodrigo

On Tue, Apr 17, 2018 at 4:34 PM, Dimitrios Galanis <notifications@github.com

**Comment by galanisd** [comment] 2018-04-17 17:10
I created an OMTD app/workflow.
omtdImporter -> PDF2XMI (PDFReader) -> IXA
It is private
https://test.openminted.eu/landingPage/application/4bd8e0ee-7953-43ae-b917-4466b253fe39

I fed it with a corpus
Results here.
https://test.openminted.eu/landingPage/corpus/a479260f-7bd3-4931-835f-4fc8c1e13cda
and here
[a50fa880-8f47-4bd2-898d-014c8d99fb2d.zip](https://github.com/openminted/Open-Call-Discussions/files/1920845/a50fa880-8f47-4bd2-898d-014c8d99fb2d.zip)

I see some ixa annotations but I was expecting more.

Any ideas? 

In case you want to test
PDFReader output is here (previous step)
[PdfReader_output.zip](https://github.com/openminted/Open-Call-Discussions/files/1920860/PdfReader_output.zip)


I assume that if you don't see any issues relevant to the above you can start uploading and the rest IXA
components. Keep in mind that each time you register a component a wrapper is generated for Galaxy.
When you delete a component the respective wrapper is not deleted.
I have opened an issue for this.
https://github.com/openminted/omtd-registry/issues/22

This issue might cause problems.
I was deleting the  old wrappers manually before testing your component.

**Comment by ragerri** [comment] 2018-04-18 13:19
Hello Dimitrios,

No, the output was not right, because there were not any annotations. It turns out there was an issue when reading the XMI format which we have solved.

I attach the results of the docker output which now looks fine. Perhaps you can give it a try now with the new version of the component (0.1.3) in the same workflow? I will then proceed uploading the rest of the components.

Thanks!

R

[corpus_out.tar.gz](https://github.com/openminted/Open-Call-Discussions/files/1924130/corpus_out.tar.gz)

**Comment by galanisd** [comment] 2018-04-18 14:15
Edited workflow to use version 0.1.3. Retested with the same input.
Output is here 
https://test.openminted.eu/landingPage/corpus/7861a770-f4fc-48d0-be61-47dfe2df1fc8
and it seems ok. Please have a look.

And one screenshot.
![ixa](https://user-images.githubusercontent.com/10739759/38937440-e12010fe-432b-11e8-8f54-cbce9d033be0.png)

Many thanks!

Dimitris

**Comment by galanisd** [comment] 2018-04-18 14:19
Probably  you can't download the output.
here you are...
[a3f3abbe-cf1c-4d35-be16-672a45004d9c.zip](https://github.com/openminted/Open-Call-Discussions/files/1924429/a3f3abbe-cf1c-4d35-be16-672a45004d9c.zip)

Forgot to say IXA took about 30 minutes for processing the 3 files. Is this OK?

**Comment by ragerri** [comment] 2018-04-18 14:28
Hello,

The output is exactly the same as mine. So, it works as it should.
Regarding processing time, it is not OK to be 30 minutes processing these
files :)

I have just run the process in my PC (normal core i5 intel 8GB RAM PC)

time docker run -v /home/ragerri/corpus_in:/corpus_in -v
/home/ragerri/corpus_out:/corpus_out -i ragerri/en-ixa-pipes-omtd:0.1.3
en-ixa-pipes.sh --input corpus_in --output corpus_out

real 3m41.934s
user 0m0.092s
sys 0m0.024s

Best,

R

On Wed, Apr 18, 2018 at 4:19 PM, Dimitrios Galanis <notifications@github.com

**Comment by galanisd** [comment] 2018-04-18 14:38
Sorry ... it was ~20 minutes...Still much slower than yours.
~4 min vs ~20.

![image](https://user-images.githubusercontent.com/10739759/38938656-b7f11b62-432e-11e8-9776-ec5f7b66a831.png)

This a test cluster that we are using ....and I think that each container gets 2-3 GB maximum. We will see what happens in the production.
@antleb @greenwoodma

**Comment by saxtouri** [comment] 2018-04-18 15:09
I confirm that each container is restricted to just 2G or RAM and 1 core of CPU.

**Comment by ragerri** [comment] 2018-04-18 15:32
Hello,

IXA pipes uses multi-threading and creating XMI for tokens, pos tags, named
entities and chunks requires (some) RAM. Thus, the processing time could be
justified by the restrictions for each container.

Thanks,

R

**Comment by ragerri** [comment] 2018-04-20 15:36
Hello,

I have been adding the rest of my components. Just two of them remain. Over
the weekend I will upload them.

Cheers,

Rodrigo

**Comment by galanisd** [comment] 2018-04-20 15:40
I see en, de, es, eu, gl, it, nl

**Comment by pennyl67** [comment] 2018-04-23 09:36
@ragerri 
When you finish uploading and testing, could you also upload here the metadata files for a final check?
Thanks

**Comment by ragerri** [comment] 2018-04-23 14:09
Hello,

There are 8 components: de, en, es, eu, fr, gl, it, nl. I attach the descriptors here as requested.

Cheers,

Rodrigo
[ixa-pipes-omtd-descriptors.tar.gz](https://github.com/openminted/Open-Call-Discussions/files/1938542/ixa-pipes-omtd-descriptors.tar.gz)

**Comment by galanisd** [comment] 2018-04-23 16:14
Thanks!

**Comment by pennyl67** [comment] 2018-04-24 08:57
Hi @ragerri 
For the metadata records, they're ok. I would only recommend that 
- you turn "public" to "false" when you upload them - just so that you can check them; remember that if metadata records are set to public you cannot modify them
- the only recommended piece of information that you might still want to add is the "resourceCreator" - important for citation purposes.
Again, these are only recommendations.
Apart from that, I think you're ok now also with the testing - @galanisd am I correct? So, we will soon inform you where to upload the metadata for the final delivery.

**Comment by ragerri** [comment] 2018-04-24 09:19
Hello Penny,

Sure, I would like to follow your recommendation and add the
resourceCreator element. Could you give me an example so I can just fill it
in with my own info?

Thanks,

R

**Comment by pennyl67** [comment] 2018-04-24 09:28
I've added in one of your descriptors the resourceCreationInfo module; if you have an XML editor, you can select the value person/group/organization in the <actorType> and then you will be asked to fill in the rest of the appropriate elements.
On the other hand, you can just give me the details (e.g. IXA group, person name or organization name or whatever) and I'll fill it in for you.
[nl-ixa-pipes-omtd-descriptorNew.zip](https://github.com/openminted/Open-Call-Discussions/files/1942085/nl-ixa-pipes-omtd-descriptorNew.zip)

**Comment by ragerri** [comment] 2018-04-25 20:37
Hello again,

I have uploaded another 4 components (the last ones) to test.openminted

en-ixa-pipe-opinion.sh
es-ixa-pipe-opinion.sh
fr-ixa-pipe-opinion.sh
nl-ixa-pipe-opinion.sh

For example, this is the landing page of en-ixa-pipe-opinion.sh

https://test.openminted.eu/landingPage/component/5f9a4850-af3a-486d-8821-60f20fff2198

I have also updated every share descriptor with the resource creation info.
In this link you can find all of them. The new ones:

https://github.com/ragerri/ixa-pipes-omtd/tree/master/absa2016

The previous ones:

https://github.com/ragerri/ixa-pipes-omtd

I think the one thing remaining is uploading the components wherever you
tell me.

Best regards,

Rodrigo

**Comment by pennyl67** [comment] 2018-04-26 08:45
@ragerri thanks; just to be sure, we now have 12 components from you, right? 
We'll get right back with the final uploading process

**Comment by ragerri** [comment] 2018-04-26 09:09
Yes, 12 components.

Cheers

R

**Comment by galanisd** [comment] 2018-04-26 09:17
For each component you have created a separate image?

**Comment by ragerri** [comment] 2018-04-26 09:22
Yes

**Comment by pennyl67** [comment] 2018-04-26 18:35
@ragerri You can proceed with the final uploading at services.openminted.eu. If you encounter any problems, please let us know. 
Thanks!

**Comment by ragerri** [comment] 2018-04-26 19:55
Done!

Best regards,

R

On Thu, Apr 26, 2018 at 8:35 PM, Penny Labropoulou <notifications@github.com

**Comment by pennyl67** [comment] 2018-04-26 20:02
@ragerri My mistake, there are a couple of things still for services.openminted.eu to be fully operational. 
Sorry, I wasn't fast enough to let you know! I'll see if we can still use the components as you have uploaded them now, so that you don't go through the same procedure again - or find some other way to do it.
Apologies,
p

**Comment by ragerri** [comment] 2018-04-26 20:23
No problem :)

Cheers,

R

**Comment by pennyl67** [comment] 2018-05-18 10:12
closing - all components and apps added at services (two apps are still private but I'm waiting for a fix to make them public)

**Closed as completed by pennyl67** 2018-05-18 10:12 UTC
Labels: Docker, Component
