### ISSUE TITLE
Unable to configure components after saving/loading workflow

### ISSUE THREAD

**Issue by reckart** [openminted/Open-Call-Discussions#10] opened 2018-04-08 23:37 UTC
I have created a workflow, configured some components and saved it:

https://test.openminted.eu/landingPage/application/89d5e9ea-32fb-45f7-bf00-1fe466e33c4f

However, when I now open the workflow again for editing and click on any of the components, the configuration area on the right of the workflow editor remains blank. I.e. I cannot reconfigure the components.

Note that the workflow has not been shared yet. It is a private workflow that I am still trying to make work.

**Comment by galanisd** [comment] 2018-04-09 16:47
When I am opening 
https://test.openminted.eu/landingPage/application/89d5e9ea-32fb-45f7-bf00-1fe466e33c4f
I am getting a "System error loading component (Server responded: Resource Not Found)".
Probably because it is private. A better message is needed here... 

In any case OMTD Registry is responsible for opening/editing workflows. For example a workflow that is created in the Galaxy editor instance is saved in OMTD Registry and is also exported/copied to Galaxy Executor. @antleb and @courado please have a look.

With @greenwoodma we have contributed mainly to the workflow execution part of the system.

- create the wrappers for Galaxy from OMTD-SHARE descr. 
- develop/debug the workflow-service that is responsible for sending a workflow execution request to Galaxy, monitoring it, getting the results when ready etc
- docker images and executors for UIMA/GATE
- etc

@greenwoodma has also contributed in the Galaxy editor. He created a version where all not needed buttons/functionalities are hidden. 

I hope that I assigned the issue to the appropriate people.

**Comment by reckart** [comment] 2018-04-09 16:54
@galanisd thanks! I could well imagine that the inability to change configurations **in the Galaxy workflow editor** after re-opening them from the **My applications** view could be an effect of the changes that @greenwoodma made to Galaxy - but it is just a guess.

**Comment by galanisd** [comment] 2018-04-09 17:05
My guess is that @greenwoodma changes are not the cause of this issue. As far as I know all changes
are in the UI. 

The workflow I think is deleted from the workflow editor after it is saved in OMTD Registry and the workflow definition file (.ga file) is kept. If the workflow definition (.ga file) is imported to workflow editor then it should work and the parameters should be editable. 
@courado Correct?

I have imported workflows manually or programmatically in Galaxy a thousand times.

**Comment by greenwoodma** [comment] 2018-04-09 17:08
Yes, I can't see this being related to changes I've made to the UI as all I've done is hidden some links and branding etc. nothing functional has changed

**Comment by reckart** [comment] 2018-04-14 13:29
![2018-04-14_10-28-43](https://user-images.githubusercontent.com/1410238/38768746-b6d634d2-3fce-11e8-8b90-bb8243ca4ef4.png)

**Comment by galanisd** [comment] 2018-04-14 14:40
This is for @greenwoodma  and @courado I think.

**Comment by greenwoodma** [comment] 2018-04-14 15:01
Yes, I can reproduce it but not sure why it happens yet. Will dig into it and see what I can find.

**Comment by greenwoodma** [comment] 2018-04-14 17:58
okay, having looked into this I have no idea what's going on. Firstly if you add another component to the workflow then the attributes appear for that one, but still not for the original ones. There are no errors in the browser console so it doesn't appear to be a client side issue.

My assumption was that it might be to do with having exported and then re-imported the workflow but trying that with a local instance of Galaxy (with all the editor changes applied) works without issue.

@galanisd could you remind me (probably by skype or e-mail) the URL of the underlying Galaxy editor instance used on test and the username/password so I can log in and poke around the UI a bit further -- I tried most of the URLs and usernames/passwords I already had but none of them seem to get me to the right place.

**Comment by greenwoodma** [comment] 2018-04-14 18:50
Okay, this is even weirder. I can't now reproduce the problem at all. Even the workflow in @reckart screenshot works (although it now has an invalid component in the workflow). @reckart does this still not work for you? Could you try a new workflow and/or a different browser?

**Comment by reckart** [comment] 2018-04-14 19:00
@galanisd had asked me to clean up components and applications to make debugging easier for him. I wonder why you are even still able to access the old one.

I have already re-uploaded the component and re-created the workflow:

https://test.openminted.eu/editWorkflowApplication/acc039d0-18c7-4a29-9c85-f7a7e30ef102

For me, the problem persists.

Tested with:

* Safari Version 11.1 (OS X)
* Chrome 65.0.3325.181 (OS X)
* Firefox 59.0.2 (OS X)

**Comment by greenwoodma** [comment] 2018-04-15 08:25
So I just tried editing that workflow and...

![screenshot from 2018-04-15 09-23-42](https://user-images.githubusercontent.com/3025272/38776452-cc57f4ec-408e-11e8-89c1-2c5e361835be.png)

as you can see it works for me I can see all the params for each component. This suggests it's something at your end rather than a platform issue. If you look at the developer tools in your browser do you see any javascript errors or anything else suspicious?

**Comment by reckart** [comment] 2018-04-15 13:20
I see an XHR error:

```
{
    "error": "Page with route '/editWorkflowApplication/acc039d0-18c7-4a29-9c85-f7a7e30ef102' not found"
}
```

and a logged error

```
[Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (route, line 0) - https://test.openminted.eu/faq/page/route?q=/editWorkflowApplication/acc039d0-18c7-4a29-9c85-f7a7e30ef102
```

However, I also see similar errors when I edit a fresh workflow where the sidebar panel appears.

```
[Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (route, line 0) -- https://test.openminted.eu/faq/page/route?q=/resourceRegistration/application
[Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (route, line 0) -- https://test.openminted.eu/faq/page/route?q=/buildWorkflow/c1c2121d-0d43-4c9a-b548-16845ada1323
[Error] Failed to load resource: the server responded with a status of 400 () (all, line 0) -- https://test.openminted.eu/api/webhooks/tool-menu/all
```

**Comment by greenwoodma** [comment] 2018-04-15 13:25
Yes, I see those errors as well (no idea what they are about). I was hoping you'd see an error when you clicked on a component, as I assumed that would be when javascript would kick in to populate the sidebar and fail for some reason.

**Comment by reckart** [comment] 2018-04-15 13:34
I checked in Safari and in Chrome - at the time when I click on a specific component for editing, nothing suspicious is logged. Also all of the AdBlocker, JSBlocker, Privacy plugins say that they have blocked nothing. In any case, the configuration of these plugins is also the same when creating a workflow from scratch and there things work as expected. Only when re-opening, it fails to work.

**Comment by reckart** [comment] 2018-04-15 13:35
@greenwoodma btw. why are you allowed to edit my unpublished workflow? ;)

**Comment by greenwoodma** [comment] 2018-04-15 13:42
@reckart ah yes, I wondered when someone would spot that. If you remember back a long way we decided on security by obscurity for Galaxy, so there is only a single Galaxy user which can see all the workflows, but you need either access to the full Galaxy UI (which I have) or the id (which you gave me in the URL) to access a workflow. As it would be impossible to guess these we are okay (we hope) but because I have the ID I can see the editor. Although that only explains why I can see the workflow in Galaxy, it doesn't explain why the platoform let's me load this URL

https://test.openminted.eu/landingPage/application/acc039d0-18c7-4a29-9c85-f7a7e30ef102

or see the editor embed in the platform UI; both of those should really be blocked by the platform as it knows which user owns which workflows.

One further question what happens if you go straight to the URL

https://test.openminted.eu/editWorkflowApplication/acc039d0-18c7-4a29-9c85-f7a7e30ef102

in a browser (which is what I'm doing) rather than clicking the edit workflow link in the registry UI? I'm wondering if that's the difference as clicking the link in the UI should cause the workflow to be re-imported and maybe it's a timing issue which I'm not seeing by going to the link directly once the workflow is already present.

**Comment by reckart** [comment] 2018-04-15 14:19
For my tests right now, I have actually used the direct links from this issue here. I didn't go through the registry. I even tried logging in first and then opening the link so that I wouldn't have to go through the login screen - but didn't help either.

**Comment by reckart** [comment] 2018-04-15 14:20
@galanisd when you open the link to the workflow above, can you click on a component and see/edit its parameters?

**Comment by galanisd** [comment] 2018-04-15 14:34
@reckart 

I opened this one
https://test.openminted.eu/editWorkflowApplication/acc039d0-18c7-4a29-9c85-f7a7e30ef102
(this is the one you asked?)

and this is what I got....
 
![screenshot from 2018-04-15 17 31 02](https://user-images.githubusercontent.com/10739759/38779566-d4c7516a-40d2-11e8-9fc6-243db1a55e5a.png)

**Comment by reckart** [comment] 2018-04-15 14:40
Hm.... **very** odd.

**Comment by greenwoodma** [comment] 2018-04-15 17:27
Agreed, very odd. I thought I could reproduce it once, but haven't managed since so maybe I was wrong. Either way it seems @reckart is the only one of the three of us who can see the problem on that workflow which really suggests to me it's something odd on his setup rather than an issue with the platform as such. Question is how common is that setup, i.e. how many others will this affect?

If it wasn't such a potentially big problem I'd suggest closing the issue as not being reproducible.

**Comment by reckart** [comment] 2018-04-15 18:20
The odd thing is that I tried three different browsers and failed with all of them. I'll try later with a different computer.

**Comment by reckart** [comment] 2018-04-19 00:10
As a temporary workaround, I simply remove the component I want to reconfigure and re-add it.

I hope the configuration of the other components doesn't break when I save again.

**Comment by reckart** [comment] 2018-04-19 12:18
@greenwoodma I have tried it in a Windows VM now using Chrome 64.0.3282.186 - I also do not get the detail elements for editing the workflow.

If you create your own workflow instead of using mine and re-open it for editing, do you also get the detail editors? Is your user somehow an admin user? What if you use a non-privileged user?

**Comment by greenwoodma** [comment] 2018-04-19 12:36
@reckart ah you're on to something. I've just tried editing my own workflow in my normal browser and it works fine. If I drop into private browsing mode though it starts behaving the same was as it does for you. Now I know I've accessed other parts of that Galaxy instance, but I wasn't aware I'd logged in, but something is clearly giving me more rights in my normal browser than when in private mode. Now I know where to look I'll start digging.

**Comment by greenwoodma** [comment] 2018-04-19 12:45
@reckart if you visit https://test.openminted.eu/galaxy and then try editing a workflow does it magically start working correctly?

**Comment by reckart** [comment] 2018-04-19 13:01
Yep, there it seems to work. I opened "0931730980607790-9b9b1d64-fe3f-4de7-88ca-bf1f788e60f5" and clicked on a component - it appeared in the right sidebar.

**Comment by reckart** [comment] 2018-04-19 13:02
sorry, misunderstood the question. Let me check again.

**Comment by greenwoodma** [comment] 2018-04-19 13:02
and now if you go back and try editing through the normal platform UI I assume it also works?

**Comment by reckart** [comment] 2018-04-19 13:03
Yes, if I open a workflow now via "my applications", I can also edit the details.

Scary!

**Comment by greenwoodma** [comment] 2018-04-19 13:05
well at least that proves my theory of what's going on, doesn't necessarily help me figure out why, but I'm guessing something to do with authorisation has got messed up with the edits I did to the workflow editor, and that visiting another unaltered page is setting the session cookies etc. up correctly.

**Comment by greenwoodma** [comment] 2018-04-19 14:24
Unfortunately I think this is a bug in galaxy rather than something I messed up when producing the cut down editor.

As we put the editor in an iframe I've been able to roll back almost all my changes to Galaxy as it already contained support for use in an iframe that hides almost exactly what we wanted to hide -- originally I assumed we'd want a full screen version as well. I've made these changes live on test.openminted.eu so you can see how it looks now. This reduces the changes I've made to essentially just changing the save button, i.e. nothing related to authorization at all, yet as far as I can see, if I start a new private browsing session the same problem occurs as before until I visit the main galaxy page in that browser session, so I think we have to put this down as a Galaxy bug :(

Unfortunately as we are now using a quite old version of galaxy, I'm not sure how easy it will be to raise this as an issue for them to look into, but I'll keep digging and see if I can spot anything obvious on the home page that differs from the editor that might cause this.

**Comment by galanisd** [comment] 2018-04-19 14:34
> to put this down as a Galaxy bug :(

Great :-)

**Comment by greenwoodma** [comment] 2018-04-19 14:36
Yes it's great it's not our bug, but it's my idea of a living hell if anyone expects me to try and fix it!

**Comment by reckart** [comment] 2018-04-19 14:37
@greenwoodma well, IMHO it'd be best to open an issue with the Galaxy people and see how they react. Maybe they have a hint that works also in the older versions - maybe not. But that has to be seen.

**Comment by greenwoodma** [comment] 2018-04-19 14:40
@reckart yes I probably will do once I've gathered a bit more info. Problem is that not only are we now on an quite old version, but we are doing the auth in a rather odd way which is where the bug probably lies, so even finding someone who can reproduce the issue is going to be tricky, but I'll see what I can do.

**Comment by greenwoodma** [comment] 2018-04-23 10:02
I've now opened an issue for this problem so hopefully one of the Galaxy devs might have an idea on how to fix it. Details are at galaxyproject/galaxy#5955

**Comment by greenwoodma** [comment] 2018-05-15 07:22
This is now fixed on test.openminted.eu thanks to some work from the Galaxy devs. The changes are checked in to our galaxy editor branch so should go live on services.openminted.eu next time that is updated.

**Closed as completed by greenwoodma** 2018-05-15 07:22 UTC
