### ISSUE TITLE
Pubrunner hackathon

### ISSUE THREAD

**Issue by jakelever** [openminted/Open-Call-Discussions#30] opened 2018-04-13 00:49 UTC
Hi, it'd be great to have a meeting next week. I'd like to confirm how to test Docker-based applications.

**Comment by greenwoodma** [comment] 2018-04-16 12:24
To make sure we are as well prepared as possible to help during the hackathon sessions could you please add/attach to this issue:

1. The landing page URL of any component/workflow you have registered
2. The OMTD-SHARE XML file for each component/workflow
3. One or two sample documents that you expect to produce sensible output for your component/workflow

**Comment by jakelever** [comment] 2018-04-17 00:59
Hi, we've got two Docker-based applications:

### Ab3P with PubRunner
Landing Page: https://test.openminted.eu/landingPage/application/1c058b30-fff2-4ffc-99d8-1bf6422c155e
OMTD-SHARE: [Ab3PwithPubRunner.zip](https://github.com/openminted/Open-Call-Discussions/files/1917765/Ab3PwithPubRunner.zip)

### OpenSesamIE with PubRunner
Landing page: https://test.openminted.eu/landingPage/application/ab4cd0ab-ef72-415b-9a79-7e07c27f1bb7
OMTD-SHARE: [OpenSesamIEwithPubRunner.zip](https://github.com/openminted/Open-Call-Discussions/files/1917766/OpenSesamIEwithPubRunner.zip)

And both those tools should give output from this example document:
[exampleInput.zip](https://github.com/openminted/Open-Call-Discussions/files/1917769/exampleInput.zip)

And the associated Docker hub page for both: https://hub.docker.com/r/jakelever/pubrunner/

**Comment by galanisd** [comment] 2018-04-17 09:20
Hello,

Galaxy is filled with old versions of wrappers for PubRunner because of this https://github.com/openminted/omtd-registry/issues/22 
which makes the whole process of testing very difficult.
@courado @antleb 

So, I deleted all of them, then I deleted your apps from Registry and re-register them

I tested "Ab3P with PubRunner" with a corpus and FAILED...I got this message
./pubrunner/openminted/Ab3P.py: No such file or directory

The reason is that Galaxy creates a "working" dir and calls your component from there.
See here for more info.
https://github.com/openminted/Open-Call-Discussions/issues/28

@pennyl67 @greenwoodma @mandiayba @reckart 
We should add in the Docker spec that the executable is runnable/visible from everywhere in the container. It seems the most common problem so far ...

**Comment by gkirtzou** [comment] 2018-04-17 10:56
@jakelever Both for the Ab3P with PubRunner and OpenSeasamIE with PubRunner, given your description I understand that your applications generate a single output document of tsv format containing only abbreviations/acronyms; thus to be semantically correct please change in the outputResourceInfo, the processingResourceType to lexicalConceptualResource, in the final version of the metadata.

**Comment by gkirtzou** [comment] 2018-04-17 14:48
@jakelever Moreover, I would like to suggest to enrich the metadata for your application for better clarity and discoverability reasons with the following:

- For the Ab3P, in your description you mention that the output is a list of all acronyms/abbreviations detected in the input corpus, thus I would propose to add in the outputResourceInfo.annotationTypes, the obligatory element of annotationType with an appropriate value from the AnnotationType Hierachy, such as [http://w3id.org/meta-share/omtd-share/SemanticAnnotationType](http://w3id.org/meta-share/omtd-share/SemanticAnnotationType) and as annotationTypeOther with free text the words: "acronyms/abbreviations".
- Similarly, for the OpenSesamIE, as in your description you mention that the output is a list of subj-predicate-obj triples, I would propose to add in the outputResourceInfo.annotationTypes, the obligatory element of annotationType with an appropriate value from from the AnnotationType Hierachy, such as [http://w3id.org/meta-share/omtd-share/SemanticAnnotationType](http://w3id.org/meta-share/omtd-share/SemanticAnnotationType) and as annotationTypeOther with free text the words: "subj-predicate-obj triples".

These type of information, would allow us to enrich also our OMTD ontology.

A couple of additional recommendations for the metadata:
- For citation reason, pleas add  resourceCreationInfo with resourceCreator.
- If you have any extra information material (e.g. publications, user manual etc.) on your software, you can use the resourceDocumentationInfo for that reason.

**Comment by jakelever** [comment] 2018-04-18 01:27
Thanks for digging into this.

@galanisd I've updated the Docker image and commands in the OMTD-SHARE so that the commands should work anywhere

@gkirtzou I've made your suggested changes to the OMTD-SHARE files.

**Comment by gkirtzou** [comment] 2018-04-18 09:16
@jakelever could you please provide me the OMTD-SHARE files, to check again and see if everything is ok? Thanks

**Comment by galanisd** [comment] 2018-04-18 12:48
> I've updated the Docker image and commands in the OMTD-SHARE so that the commands should work anywhere

You uploaded them in test.openminted.eu? 
Landing pages?

**Comment by jakelever** [comment] 2018-04-19 21:09
Hi, apologies I was teaching all of yesterday.

Here is the updated OMTD-SHARE files. They're from the updated components (through the original landing pages). And I've updated the Docker image at jakelever/pubrunner .

[Ab3PwithPubRunner_v2.zip](https://github.com/openminted/Open-Call-Discussions/files/1929782/Ab3PwithPubRunner_v2.zip)
[OpenSesamIEwithPubRunner_v2.zip](https://github.com/openminted/Open-Call-Discussions/files/1929783/OpenSesamIEwithPubRunner_v2.zip)

**Comment by galanisd** [comment] 2018-04-19 22:28
Hi,

- Deleted the old versions from test.openminted.eu
- Reregistered the XML files that you sent.
- Tested Ab3P with a corpus. Got the following..

`Traceback (most recent call last):
  File "/pubrunner/openminted/Ab3P", line 22, in <module>
    assert os.path.isdir(args.output)
AssertionError`

I am just guessing...Do you check if the provided output dir exists?
The directory should be created if it does not exist. For some reason Galaxy is not creating it.
See also https://github.com/openminted/Open-Call-Discussions/issues/28#issuecomment-381199289
we had the same issue.  

Dimitris.

**Comment by jakelever** [comment] 2018-04-21 00:51
@galanisd , yep that is correct. I've fixed that bug and updated the Docker image

**Comment by gkirtzou** [comment] 2018-04-23 09:42
@jakelever As far as the metadata records, I have no further comments/recommendations. I am just waiting to verify via the testing performed by Dimitris that the information provided for running the components is correct, in order to consider them as final versions. Please in the final version, do not use the latest image for your components, but a versioned one. This way the platform will be able to claim reproducibility for your components.

**Comment by galanisd** [comment] 2018-04-23 11:06
This is  the landing page for PubRunner?
https://test.openminted.eu/landingPage/application/1c058b30-fff2-4ffc-99d8-1bf6422c155e
I got a "System error loading component (Server responded: Access is denied)" message. 

I assume that the app is private and  the latest version of OMTD Registry  does not allow to anyone except the owner to get access.
@antleb ?

@jakelever 
If you want you can make it public so that I can test.

**Comment by jakelever** [comment] 2018-04-24 02:10
Hi @gkirtzou and @galanisd , I've updated the OMTD to use a versioned Docker image (jakelever/pubrunner:0.3.1). Attached are the OMTD XML files just in case. I've also made the two applications public.

[Ab3PwithPubRunner_OMTD.zip](https://github.com/openminted/Open-Call-Discussions/files/1940590/Ab3PwithPubRunner_OMTD.zip)
[OpenSesamIEwithPubRunner_OMTD.zip](https://github.com/openminted/Open-Call-Discussions/files/1940591/OpenSesamIEwithPubRunner_OMTD.zip)

**Comment by galanisd** [comment] 2018-04-24 11:59
@jakelever 
Thanks! For some reason the update you did it didn't triggered the process of generating a new Galaxy wrapper (and deleting the old one).
@antleb @courado 

But no problem. I re-registered 
https://test.openminted.eu/landingPage/application/PubRunnerDGv3
and everything worked as expected.
 
Then I ran a test.
PubRunner + Thalamus corpus
and got results.

![screenshot from 2018-04-24 14 41 59](https://user-images.githubusercontent.com/10739759/39185150-e5a8b9bc-47ce-11e8-81ba-035290695dbe.png)

The output is here
https://test.openminted.eu/landingPage/lexical/4b747bd2-a9dc-4d58-ba1f-07b4844a6ef0

Unfortunately the option to download the result is not provided. 
Screenshot
![screenshot from 2018-04-24 14 51 38](https://user-images.githubusercontent.com/10739759/39185260-4a7fd604-47cf-11e8-8ddb-f9412bf646e8.png)
@antleb @courado 

However, I located the output in Galaxy and download it. Seems ok.
...please have look...

[Galaxy10-component_output__abbreviations.tsv.zip](https://github.com/openminted/Open-Call-Discussions/files/1942604/Galaxy10-component_output__abbreviations.tsv.zip)

**Comment by jakelever** [comment] 2018-04-25 19:26
@galanisd Thank you for testing this out

**Comment by pennyl67** [comment] 2018-04-26 18:42
@jakelever You can now proceed to the uploading of your final applications at services.openminted.eu. If you have any problems, please let us know.
Thanks

**Comment by pennyl67** [comment] 2018-04-26 19:56
@jakelever My mistake, please refrain from uploading at services.openminted.eu until further notice.

**Comment by gkirtzou** [comment] 2018-05-09 10:55
Dear @jakelever you can now proceed to the uploading of your applications at https://services.openminted.eu/home 

Just, one final suggestion for the metadata records is to add in both input and output resource info the language(s) that your application can handle. 

If you encounter any problems, please let us know. Please also let me know when you have uploaded the applications to the production site. 
Thanks!

**Comment by gkirtzou** [comment] 2018-05-11 11:16
Please, when you upload your applications, please keep them private and send me the metadata here, so I could check them.

Also, you could add the deliverable from the tender call to your git-hub repository (if you have) and add them as documentation to the metadata of your software.

Thanks.

**Comment by jakelever** [comment] 2018-05-15 23:32
@gkirtzou I uploaded the OMTD-SHARE files to the main platform (https://services.openminted.eu) but forgot that the "Make Public" flag is in the XML file. So I've inadvertently made both applications public and didn't make the suggested edits. I'm working on getting the ADAPT document finished so would attach that later. Is there any way they could be made private again?

Ab3P with PubRunner: https://services.openminted.eu/landingPage/application/1c058b30-fff2-4ffc-99d8-1bf6422c155e
OpenSesamIE with PubRunner: https://services.openminted.eu/landingPage/application/ab4cd0ab-ef72-415b-9a79-7e07c27f1bb7

**Comment by gkirtzou** [comment] 2018-05-16 07:21
@jakelever Unfortunately, you cannot revert them to private once you went public. I can try to contact the tech team of the registry and delete them, so you could reupload them as private. I will let you know when this is done. 

Please if you adapt the documents with the suggestions, do send them to check independently whether the previous versions are still registered.

**Comment by gkirtzou** [comment] 2018-05-16 10:47
@jakelever the suggestions I have proposed (language and add the deliverables as an extra documentation source) are optional. Do you want them to add them? If yes, let me know so I could ask to remove the apps. Otherwise, the are in good status and I was able to ran them perfectly in the platform. Let me know how you want to processed.

**Comment by jakelever** [comment] 2018-05-16 21:46
@gkirtzou . It's fine. I'm happy with the status of the applications. If we have to make any updates in the future, I can add the metadata then.

**Comment by gkirtzou** [comment] 2018-05-17 08:08
@jakelever As you wish. Your app have correct metadata and can run in the platform successfully. So I am closing the issue. Cheers.

**Closed as completed by gkirtzou** 2018-05-17 08:08 UTC
Labels: Docker, Application
