### ISSUE TITLE
Àlex Hackathon

### ISSUE THREAD

**Issue by abravo84** [openminted/Open-Call-Discussions#27] opened 2018-04-12 14:16 UTC
Hello! Now I am building a docker image with my JAR file. So, I will probably need help to integrate my image on the platform. If everything is fine, I'll send you a message. But at the moment I'm in for the hackathon.

Thank you for your support!

**Comment by greenwoodma** [comment] 2018-04-16 12:24
To make sure we are as well prepared as possible to help during the hackathon sessions could you please add/attach to this issue:

1. The landing page URL of any component/workflow you have registered
2. The OMTD-SHARE XML file for each component/workflow
3. One or two sample documents that you expect to produce sensible output for your component/workflow

**Comment by abravo84** [comment] 2018-04-16 15:03
Hi Mark!

Thank you for your support! I registered a JAR file on the Test Platform, but it is not working. However, it is not a problem, because now we are working on a docker image. So, we will try to register a docker component.

The Dockerfile copies all necessary files: source code, jar files not included on maven and multiple resources as a SQLite file about 20Gb. The docker installs the jar files in the local repository of maven, and the package the project generating a final JAR. This JAR file is executed using two parameters: an input folder with XML files and an output folder to provide the generated GATE documents. 

Now I am trying to update my docker on docker hub. Then, I will register my docker file and I will write the OMTD form.

As input example I have a dataset on the Test Platform: 
https://test.openminted.eu/landingPage/corpus/86ba1d12-beb3-4b66-883d-167728042906

And I have attached an output file of my system (GATE Document)
[journal.pone.0194749.xml.zip](https://github.com/openminted/Open-Call-Discussions/files/1915840/journal.pone.0194749.xml.zip)

Best,

à.

**Comment by abravo84** [comment] 2018-04-17 10:47
Hello!

I add the Docker Hub URL of my component:
https://hub.docker.com/r/abravp/scisum/

The component url on the Test Platform:
https://test.openminted.eu/landingPage/component/04ba9a35-6c77-4c42-88be-e7b218a0ea68

The OMTD-SHARE XML is attached in this message
[04ba9a35-6c77-4c42-88be-e7b218a0ea68.xml.zip](https://github.com/openminted/Open-Call-Discussions/files/1919316/04ba9a35-6c77-4c42-88be-e7b218a0ea68.xml.zip)

Best,

à.

**Comment by gkirtzou** [comment] 2018-04-17 11:33
@abravo84
**1)**
In the  distributionInfos do the following change in order to be consistent with the OMTD specifications and so as your component will be able to called in the OMTD platform:
- Change the distributionLocation to _abravp/scisum:version_, in order to pull correctly your Docker image.  It is good to have a tagged version in order to support reproducibility, thus the _version_ above. 
- Change the command to docker _process.sh_  (the omtd executor you created) and verify that your omtd executor is available to run from everywhere with the docker image. See also: https://github.com/openminted/Open-Call-Discussions/issues/28#issuecomment-381683553

**2)**
There is no need to describe the input and output folder as a parameter in the metadata description. There are covered by the inputContentResourceInfo and outputResourceInfo respectively.

**3)** Optional
- Could you add resourceCreationInfo with resourceCreator? It's not mandatory but it will help the citation process
- If you have any extra information material (e.g. publications, user manual etc.) on the components, you can use the resourceDocumentationInfo for that reason.

**Comment by abravo84** [comment] 2018-04-17 14:54
@gkirtzou 

Thank you so much!

About 1)

- I will push me docker image with the corresponding version in the tag.

- Regarding the second point, I do not understand very well, how can I change the command of my process.sh? Using absolute paths?

About 2) Ok! Then, I will update the descriptor without parameters in the metadata.

**Comment by gkirtzou** [comment] 2018-04-17 14:57
A quick question, I notice that in the inputContentResourceInto you declared that your input is of type  XML and the annotation type set to "Structural annotation type". That means, that your input need to be in XML format and already annotated in that level in order to perform the summarization, correct? 

Furthermore, as output you have declared the annotation type as  "Structural annotation type", along with other, that means that you keep the initial structural annotation of the input? If yes, please add the previousAnnotationTypesPolicy element with value "keep" or "modify" depending on what your component actually does.

**Comment by gkirtzou** [comment] 2018-04-17 15:06
> Regarding the second point, I do not understand very well, how can I change the command of my process.sh? Using absolute paths?

I mean to change the element _command_ from "docker run -v /var/data/plos_one:/input -ti -v /var/data/plos_one_output:/output openminted_scisumservices process.sh --input /input --output /output"  to just "openminted_scisumservices process.sh" or "process.sh", whichever is the command you are using to invoke your application. 

Note that this command needs to be accessible from everywhere in the image, better not to use absolute paths, but add it to /usr/bin.

**Comment by abravo84** [comment] 2018-04-17 15:06
First question yes. Specifically, the input of my application is a path with articles in XML format, such as Plos ONE articles.

About the second one, I return the same information (I keep as "Original markups") including new summarization features, but as a GATE document (it is also a XML file, but with different structure).

**Comment by gkirtzou** [comment] 2018-04-17 15:20
Cool, then if you add the previousAnnotationTypesPolicy element added with value "keep". Also, I would suggest to declare your component as application, since it is a complete end-to-end process.

**Comment by abravo84** [comment] 2018-04-17 15:26
Yes, it is a complete end-to-end process, so I will upload a new application. Thanks!

**Comment by abravo84** [comment] 2018-04-18 08:03
@gkirtzou 

Hi Katerina! I have attached my _process.sh_ and my _dockerfile_, because I have a question. My command _"docker run -v /var/data/plos_one:/input -ti -v /var/data/plos_one_output:/output openminted_scisumservices process.sh --input /input --output /output"_ has these parameters because my _process.sh_ read and map the folders, if I describe my docker command as "openminted_scisumservices process.sh", will it work?
In addition, I copy the process.sh to /bin/process.sh as you can observe in the Dockerfile.
[scisumservices.zip](https://github.com/openminted/Open-Call-Discussions/files/1922980/scisumservices.zip)

**Comment by gkirtzou** [comment] 2018-04-18 10:03
(1) From the Dockerfile you provided me, I can see that you add the process.sh script in the /bin, thus it should be callable from everywhere with the docker image. Thus just the process.sh command should be enough. 

(2) In OMTD platform we generate a command similar to the one you provided initially 
, i.e. _"docker run -v /var/data/plos_one:/input -ti -v /var/data/plos_one_output:/output openminted_scisumservices process.sh --input /input --output /output"_,  for running the docker images taking into consideration the OMTD platform requirements. Thus I am asking only for the omtd-executor you have defined. I believe that it could work, since we will add the input, output folder as declared in the specifications. 

(3) Could you please also send me the updated OMTD-SHARE descriptor, to verfiy that everything is correctly defined in the metadata?

**Comment by abravo84** [comment] 2018-04-18 10:45
I cannot modify the OMTD-SHARE descriptor from the test platform, I think it is because the component is public. I will upload a new application with your changes. About the omtd-executor, I do not remember defining anything with this name.

**Comment by gkirtzou** [comment] 2018-04-18 11:27
@abravo84 Yes, if you had declare it as public, you cannot edit it. You would need to upload a new version or do the changes in the xml and send me that to check again

As omtd-executor, I am naming the command used for invoking the component(s) in the docker image. Sorry for confusing you.

**Comment by abravo84** [comment] 2018-04-18 11:55
Ah! Ok! :) 

I have changed my local XML descriptor file and it is attached:
1) I have removed the input and output information 
2) the previousAnnotationTypesPolicy is keep
3) I have changed the docker url (https://hub.docker.com/r/abravp/scisum:)
4) I have changed the docker command (docker run openminted_scisumservices process.sh)
[04ba9a35-6c77-4c42-88be-e7b218a0ea68.xml.zip](https://github.com/openminted/Open-Call-Discussions/files/1923845/04ba9a35-6c77-4c42-88be-e7b218a0ea68.xml.zip)

When I upload the new application I will follow the same considerations.

**Comment by gkirtzou** [comment] 2018-04-18 13:05
A few small explanations and questions:
1) When we have an OMTD_SHARE description with the componentDistributionForm as dockerImage, we assume that the image is upload to https://hub.docker.com/, (as requested by the [guidelines](https://guidelines.openminted.eu/sharing-components-as-dockerised-images.html)), thus we only need its name:version in order to pull it correctly. Imagine that we need to perform within the platform the following command
docker pull component_name:version , where in the OMTD_SHARE description 
<ns0:distributionLocation>component_name:version</ns0:distributionLocation>
Thus in your case, it should be				<ns0:distributionLocation>abravp/scisum</ns0:distributionLocation>

Please remember, in the final registered version of the component, to use a tagged version of your image for reproducibility reasons. This way it is safe that the code of your component won't change and others could reuse it to reproduce the same results.

2) For the DockerFile your had send me I understood that the scisumservices is a working directory. If I am not mistaken this is ignore within the galaxy engine that we run the workflow. I am pretty confident that if you use only the process.sh as command, if that is declared globally (which is given your dockerfile), it will run successfully.

I am attaching the metadata record, with the above corrections 
[AlexV2.xml.zip](https://github.com/openminted/Open-Call-Discussions/files/1924089/AlexV2.xml.zip)

**Comment by gkirtzou** [comment] 2018-04-18 13:06
You could delete the old component and use the xml registration to register the updated metadata. Let me know how it goes.

**Comment by abravo84** [comment] 2018-04-19 07:27
I am sorry. Yesterday afternoon we had a deadline, and now I will teach until noon. This afternoon I will upload my new docker image and I will register with the AlexV2.xml. Only a question, the docker image location in the XML is **abravp/scisum**, should I change it for **abravp/scisum:1.0.0**? Or the platform joins the distributionLocation with the version?

**Comment by gkirtzou** [comment] 2018-04-19 07:53
No the platform does not join the distribution location with the version. If you need to register a specific version to the platform you need also to declare it to the distributionLocation field. If in distribution location you say  **abravp/scisum:1.0.0** the platform will retrieve the image of version 1.0.0, if you say just **abravp/scisum** the platform will retrieve the latest. As I have mention previously, it is recommended for reproducibility reason to register tagged version of images. This way you ensure that even if we need to restore the contents of the platform, we will retrieve the correct version of components.

**Comment by greenwoodma** [comment] 2018-04-19 15:36
Sorry to not have done this before but we could do with organising a time for a quick online chat (i.e. the hackathon). The original plan was to try and do that this week. Would you have time tomorrow to talk? I can currently do any time between 08:00BST and 16:00BST.

**Comment by abravo84** [comment] 2018-04-19 22:56
@gkirtzou 

Hello! I just uploaded the new component with your XML Descriptor:

https://test.openminted.eu/landingPage/component/9503494d-c09e-4b9a-80b8-10945c38ef6d

Now the Docker image is: abravp/openminted_scisumservices:1.0.0

I hope it's all okay! :)

@greenwoodma 

Mark, if everything is fine, we will not need to talk. Otherwise, I could chat about 10:30BST, my hangout is alex.bravo@upf.edu.

Best,

à.

PS: If you think it is appropriate,, I can create a new application with my Docker.

**Comment by gkirtzou** [comment] 2018-04-20 07:12
@abravo84 I will check the metadata and let you know. You will receive my answer by tomorrow, as today I won't be able to do it. I am sorry for the delay.

**Comment by abravo84** [comment] 2018-04-20 07:19
No problem @gkirtzou ! :) Yesterday, I had to make some modifications and add new features to our system. You could answer on Monday. Take your time!

Best,

à.

**Comment by gkirtzou** [comment] 2018-04-23 11:01
@abravo84  I have no further comments/recommendations for the metadata themselves. I will try to test your component and I will let you know how that goes.

**Comment by abravo84** [comment] 2018-04-23 13:45
@gkirtzou ok! thank you for your support! :smile:

**Comment by gkirtzou** [comment] 2018-04-25 15:04
@abravo84 I have created a private application (omtdImporter + your component) and I ran it with the corpus you have provided me. I got the following error

```
INPUT = tmp
OUTPUT = /srv/galaxy/database/jobs_directory/001/1019/working/out/
Exception in thread "main" java.lang.NullPointerException
	at java.util.Arrays.sort(Arrays.java:1246)
	at edu.upf.taln.scisumservices.SciSumService.main(SciSumService.java:722)
```

Do you any idea what could have gone wrong?

**Comment by abravo84** [comment] 2018-04-25 15:13
@gkirtzou Yes! In the line 722 I sort the list of files. So, the input folder is empty.

**Comment by gkirtzou** [comment] 2018-04-26 09:35
@abravo84 I am running your component locally, and it seems to progress well. It is weird that I got that error, as the first step  (omtdImporter) is just to upload the input corpus to the workflow engine. I will check again and I will try to understand what went wrong.

**Comment by abravo84** [comment] 2018-04-26 10:24
@gkirtzou Thank you! I have attached 5 articles from Plos ONE.

Best,

à.
[plos_one.zip](https://github.com/openminted/Open-Call-Discussions/files/1950715/plos_one.zip)

**Comment by gkirtzou** [comment] 2018-04-26 10:57
I was able to run your component locally with the input you have provided me previously, and I got these results. Could you verify if are ok? I will try to run it again though the platform to see if we get the same error. 
[output.zip](https://github.com/openminted/Open-Call-Discussions/files/1950803/output.zip)

**Comment by gkirtzou** [comment] 2018-04-26 14:39
I think I found out the problem. The `tmp` directory is not found since just before you call 

`java -Xmx5g -jar target/scisumservices-jar-with-dependencies.jar ${INPUT} ${OUTPUT}`

you are changing the directory `cd /scisumservices`. If you remove this command and use absolute path in invoking your software it would probably work. Change it as follow:
` java -Xmx1g -jar /scisumservices/target/scisumservices-jar-with-dependencies.jar ${INPUT} ${OUTPUT}`

Note also, that I shrink the requested memory, due to the constrains of the platform. At least for now.

**Comment by abravo84** [comment] 2018-04-26 15:15
Hi @gkirtzou !

Sorry for my late response! Ok, then, I have to compile my docker image again changing the "java" command in the process.sh, right? Also the memory?

**Comment by gkirtzou** [comment] 2018-04-26 15:18
Removing the cd command and changing the java command to the one I have provided you, I think will allow us to find the tmp (ie input) folder correctly.

**Comment by abravo84** [comment] 2018-04-26 15:41
ok! this will take a few hours... When the docker image is uploaded I text you!

**Comment by gkirtzou** [comment] 2018-04-27 09:15
@abravo84 I saw that in the spreadsheet with the h/w requirements you said that the mimimum memory you require is 4G. That means that it cannot ran with any less than that right?

**Comment by abravo84** [comment] 2018-04-27 09:54
Hi @gkirtzou! (i am uploading the new docker image...). 
I do not think so... You can try,  If you do not have enough memory, the application will return a memory error.

**Comment by gkirtzou** [comment] 2018-04-27 12:09
Let me know when the image have been upload, so I will try again and see.

**Comment by abravo84** [comment] 2018-04-27 15:10
@gkirtzou The docker image is available! :)

**Comment by gkirtzou** [comment] 2018-05-02 13:58
@abravo84 I was able to run your image giving to the container 6.6GB of memory. Unfortunately, this seems that it is not enough to ran successfully your component, despite that you had declared that the minimum possible memory requirement is 4 GB. The last lines of the log were the following:

```
2018-05-02 13:42:43 INFO  DocumentImpl - Extract Graph - executed in 143701 ms.
2018-05-02 13:42:46 INFO  DocumentImpl - Extract Graph - END.
2018-05-02 13:42:46 INFO  DocumentImpl - Extract (spot and sanitize) Meta-annotations (projects, funding agencies, ontologies, etc.) - START...
2018-05-02 13:42:50 INFO  DocumentImpl - Spot Meta-annotations (projects, funding agencies, ontologies, etc.) - executed in 575 ms.
2018-05-02 13:42:50 INFO  DocumentImpl - Sanitize Meta-annotations (projects, funding agencies, ontologies, etc.) - executed in 36 ms.
2018-05-02 13:42:53 INFO  DocumentImpl - Extract (spot and sanitize) Meta-annotations (projects, funding agencies, ontologies, etc.) - END.
2018-05-02 13:42:53 INFO  DocumentImpl - Extract Coreference module is disabled, thus not executed. Change the module configuration of the library to enable it.
2018-05-02 13:42:53 INFO  DocumentImpl - Extract Causality module is disabled, thus not executed. Change the module configuration of the library to enable it.
2018-05-02 13:42:53 INFO  DocumentImpl - Extract Terminology (candidate terms) module is disabled, thus not executed. Change the module configuration of the library to enable it.
2018-05-02 13:42:53 INFO  DocumentImpl - Sentence rhetorical classification - START...
2018-05-02 13:42:57 INFO  RhetoricalClassifier -    - Enabled sentence language filter --> sentences to annotate rhetorically: 284 (num sentences filtered out: 0 over 284)
2018-05-02 13:43:01 INFO  RhetoricalClassifier -    - Enabled sentence language filter --> sentences to annotate rhetorically: 279 (num sentences filtered out: 0 over 279)
2018-05-02 13:51:05 INFO  DocumentImpl - Sentence rhetorical classification - executed in 488330 ms.
2018-05-02 13:51:15 INFO  DocumentImpl - Sentence rhetorical classification - END.
/bin/process.sh: line 30:    17 Killed                  java -Xmx5g -jar /scisumservices/target/scisumservices-jar-with-dependencies.jar ${INPUT} ${OUTPUT}
```
I will see if we could provide more ram, could you please verify that your component can run with the minimum requirement you have declared?

**Comment by gkirtzou** [comment] 2018-05-02 14:02
Let me tell you that I ran the component with this corpus https://test.openminted.eu/landingPage/corpus/86ba1d12-beb3-4b66-883d-167728042906,

**Comment by gkirtzou** [comment] 2018-05-03 13:08
The only thing that I could think of is if you are doing any tokenization/segmentation within your component, whether there is a problem ending with extremely big sentences, due to tables that a publication might contain. 

See also here : https://github.com/openminted/Open-Call-Discussions/issues/33#issuecomment-385049462

**Comment by abravo84** [comment] 2018-05-03 14:57
Hi @gkirtzou! I am checking my component with 4Gb of memory. As soon as I have results, I'll tell you.

**Comment by abravo84** [comment] 2018-05-04 07:19
@gkirtzou I have tested my docker with my corpus (5 files) and it worked with 5Gb of memory, so I have changed the Minimum Required Memory in the Google Sheet.

**Comment by gkirtzou** [comment] 2018-05-04 07:24
Is this the corpus you tested? https://test.openminted.eu/landingPage/corpus/86ba1d12-beb3-4b66-883d-167728042906

**Comment by abravo84** [comment] 2018-05-04 07:34
Yes! I have attached the same corpus in this message and also the corpus is included in the docker image ('/scisumservices/plos_one')
[plos_one.zip](https://github.com/openminted/Open-Call-Discussions/files/1973557/plos_one.zip)

**Comment by gkirtzou** [comment] 2018-05-04 07:51
Ok then I wonder why when I ran the same corpus in our infrastructure (docker images via the galaxy workflow engine) its memory grows to 6.6GB (upper limit) and requires more. Since the system has no more memory to offer, it ends up killing it. I will try once more just to be sure.

**Comment by gkirtzou** [comment] 2018-05-05 19:08
We were able to give more memory to the application and I have successfully ran your software. In the attachement you would find the output. Could you check that it is ok? 
[OutputCorpus.zip](https://github.com/openminted/Open-Call-Discussions/files/1976974/OutputCorpus.zip)

**Comment by abravo84** [comment] 2018-05-07 08:21
@gkirtzou YES!!! :) The relevant features are described in the deliverable 3. 

Best,

à.

**Comment by gkirtzou** [comment] 2018-05-07 09:15
@abravo84  Perfect! Then the testing from our part has finished. The metadata record are also ok. I will let you know when you can upload it to the official platform. :)

**Comment by gkirtzou** [comment] 2018-05-09 11:56
Dear @abravo84  you can now proceed to the uploading of your component at https://services.openminted.eu/home

Just, some final suggestions, not obligatory but recommended, for the metadata record are
-  Add in both input and output resource info the language(s) that your component can handle.
-  Complete the documentation info, with user manuals & publication for citation.
-  Add the resourceCreator with contact with your self, for citation reasons

Please, when you upload your component, create the appropriate workflow so that someone could run your component using the workflow editor. For more info see https://openminted.github.io/releases/workflow-editor/
Please also let me know when you have uploaded the your component to the production site.
If you encounter any problems, please let us know.
Thanks

**Comment by abravo84** [comment] 2018-05-10 11:16
Ok @gkirtzou! I have a question, my component only works with English, and I have defined "English" in my inputContentResourceInfo and outputResourceInfo. So should I add this information in other place? And also I have my mail in the Contact field.

**Comment by gkirtzou** [comment] 2018-05-10 11:25
@abravo84 If you have defined english in inputContentResourceInfo and outputResourceInfo is sufficient. 

It is nice to "duplicate" of the contant field also to the resourceCreator.  This is the place where someone would look for reasons of attribution.

Also, note that when you create an application, you wiil be asked to fill in a metadata record. Some tips for filling it in - so that they are discoverable by the users but also that users can cite you and your resource. 
- Give the application a unique name that humans can read and short enough
- Give an explanatory description; remember you can re-use the description of the component(s) in the workflow accumulatively
-  Add in the inputProcessingResourceInfo the information of the first component used in the workflow (the one after omtdImpoter), and in the outputResourceInfo the information of the last component; if the annotations from previous components are retained in the final output, please add those as well
-  (optionally) You can use the relations set with the relation "hasPart" to document the components used in the workflow - it can be repeated multiple times.

**Comment by abravo84** [comment] 2018-05-10 11:48
ok! It is not public yet. I do not know if you can check it:
https://services.openminted.eu/landingPage/component/e5042dcd-14b9-4761-9263-6f56c73c2188

**Comment by gkirtzou** [comment] 2018-05-10 11:56
I cannot see it. Could you please send me the xml file, so I can validate that everything is ok? Then you could make it public.

**Comment by abravo84** [comment] 2018-05-10 11:58
Ok! It is attached. Also should I register my corpus?
[e5042dcd-14b9-4761-9263-6f56c73c2188.xml.zip](https://github.com/openminted/Open-Call-Discussions/files/1991513/e5042dcd-14b9-4761-9263-6f56c73c2188.xml.zip)

**Comment by gkirtzou** [comment] 2018-05-10 12:49
I am not sure if your corpus is required in the production site. I would have to ask. 
Could you please create an application for your component as well?

**Comment by abravo84** [comment] 2018-05-10 13:44
You mean the appropriate workflow?

**Comment by gkirtzou** [comment] 2018-05-10 13:59
Yes an appropriate workflow that a non expert user could run your component. Thanks

**Comment by gkirtzou** [comment] 2018-05-11 11:18
Please, when you create an application so that a non-expert user could run it, please keep itprivate and send me the metadata here, so I could check them.

Also, you could add the deliverable from the tender call to your git-hub repository (if you have) and add them as documentation to the metadata of your software.

Thanks.

**Comment by abravo84** [comment] 2018-05-11 13:03
Ok! So, the component is ok and then I can create the application

**Comment by gkirtzou** [comment] 2018-05-11 14:01
Yes you can proceed creating an application. Could you please send the metadata description of the app, so that I could provide feedback?  Also, could you run with some input and verify that you get what is  expected?

Since your component consumes xml files, it would be good to provide a corpus for testing. Please send me the metadata for the corpus as well.

Please keep everything private until it is fully tested.

**Comment by abravo84** [comment] 2018-05-14 08:34
Hi! I am trying to upload the corpus, but I always receive:
**Error uploading Corpus (Server responded: undefined)**

I have attached the corpus.
[plos_one.zip](https://github.com/openminted/Open-Call-Discussions/files/1999931/plos_one.zip)

**Comment by pennyl67** [comment] 2018-05-14 10:41
Hi @abravo84
I have reported this to the tech team and let you know

**Comment by gkirtzou** [comment] 2018-05-16 12:19
@abravo84 the problem with the AAI has been resolved. Could you please upload now your corpus and test that your component works as expected, Please keep everything private until you are sure that they work perfect.

**Comment by gkirtzou** [comment] 2018-05-18 07:59
@abravo84 I am taking the initiative to create a workflow for testing your component. I will let you know how that goes.

**Comment by gkirtzou** [comment] 2018-05-18 08:57
The metadata of your component are perfect. Could you please make it public?

**Comment by abravo84** [comment] 2018-05-18 09:22
@gkirtzou Sorry for my delay, I've been pretty busy this week. I have now tried to upload the corpus, but I get the same error. I have attached the screenshot of my error.

Now, my component is publicly available.

Best,

[Screenshot from 2018-05-18 11-15-56.png.zip](https://github.com/openminted/Open-Call-Discussions/files/2016226/Screenshot.from.2018-05-18.11-15-56.png.zip)

**Comment by gkirtzou** [comment] 2018-05-18 10:30
I have created an application for your component which runs as expected. You could find it here: 
https://services.openminted.eu/landingPage/application/91ea0d94-7657-4cc9-9846-29b54cf047bf

**Comment by gkirtzou** [comment] 2018-05-18 10:48
@abravo84 Ok, I cannot understand what might the error be. Does the corpus have the expected structure? That is create a zip file that contains at least one publication.The zipped file should include a: 
- the "fulltext" folder, that will contain all publications  - mandatory,  
- the "metadata" folder, that will contain the metadata records of each file - not mandatory
- the "license" folder, that contains information about the license of each file - not mandatory
- the "abstract" folder, that contains the abstracts of publications (if available) - not mandatory

**Comment by abravo84** [comment] 2018-05-18 10:56
@gkirtzou Yes! I attached the sample some messages before, and this file is the same in the text platform.

**Comment by gkirtzou** [comment] 2018-05-18 11:02
Ok,. I would send a message to the tech team to check what could go wrong. 

As a solution I propose this : I have also uploaded the sample you have provided with the 3 xml files, and I had no problem doing so. We could make public this one, I just need to verify what licence should be paired with.

**Comment by abravo84** [comment] 2018-05-18 13:19
Ok! Thanks! It is a Creative Commons Attribution 4.0. But my sample contains 5 xml files.

**Comment by reckart** [comment] 2018-05-18 13:20
@abravo84 CC-BY is great for resources, but it is not suitable for software. A "comparable" alternative for software would be e.g. the Apache license (i.e. liberal with an attribution clause).

**Comment by gkirtzou** [comment] 2018-05-18 13:25
@abravo84 for some reason I kept only 3 xml. I downloaded again from here, I will try to uploaded and send you the metadata to check if they are ok the info.

**Comment by gkirtzou** [comment] 2018-05-18 14:16
@abravo84 Could you check the metadata of the corpus? If you are ok, I could make it public as well
[Alex_Corpus.xml.zip](https://github.com/openminted/Open-Call-Discussions/files/2017227/Alex_Corpus.xml.zip)

**Comment by abravo84** [comment] 2018-05-18 14:48
YES! I is correct :)

**Comment by gkirtzou** [comment] 2018-05-21 12:19
@abravo84 
Here is your sample corpus public : https://services.openminted.eu/landingPage/application/91ea0d94-7657-4cc9-9846-29b54cf047bf
and here is an application (public) for testing your component : https://services.openminted.eu/landingPage/application/91ea0d94-7657-4cc9-9846-29b54cf047bf

There is nothing else to do here. So I am closing the issue.

Cheers

**Closed as completed by gkirtzou** 2018-05-21 12:19 UTC
Labels: GATE, Docker, Component
