### ISSUE TITLE
VineSum hackathon

### ISSUE THREAD

**Issue by AlexJoom** [openminted/Open-Call-Discussions#19] opened 2018-04-11 13:19 UTC
We don't need technical support

**Comment by greenwoodma** [comment] 2018-04-13 09:08
In preparation for the hackathon I've been having a quick glance over all the different components and I've noticed a bit of an issue with yours.

The main issue is that the jar file doesn't contain any OMTD-SHARE descriptors as required by the interoperability guidelines. The jar file does contain a file `META-INF/eu.openminted.share/DESCRIPTORS.TXT` although our code looks for `META-INF/eu.openminted.share/descriptors.txt` -- this might be a mismatch between different bits of documentation/guidelines, sorry. However, even if the file was read correctly it contains relative paths to UIMA descriptors when it should point to OMTD-SHARE descriptor files.

The reason you can register your component on the platform is because as a fall back if we find no descriptors we analyse the class files directly to produce the OMTD-SHARE XML descriptor which you will have seen upon registering your component. The problem is that we might not always be able to extract all the relevant information this way, which is why we ask you to include the descriptor within the jar file.

The easiest way to do this is to use the Maven plugin we've developed the attempts to autogenerate the OMTD-SHARE XML files for you. Full details of how to use that can be found at: https://builds.openminted.eu/view/WP%205.2/job/OpenMinTeD%20SHARE%20Annotations/eu.openminted.share.annotations$omtd-share-annotations-doc/doclinks/1/

Note that because you will need to push your own component to Maven central and hence avoid snapshot versions of dependencies you should use version 3.0.2.5 rather than 3.0.2.6-SNAPSHOT as recommended in the documentation.

Any problems with this let us know and we'll do our best to help.

**Comment by AlexJoom** [comment] 2018-04-13 13:53
Thanks for your help @greenwoodma 
We are proceeding with the fixes and get back to you in case we need help.

Best,

**Comment by greenwoodma** [comment] 2018-04-16 12:23
To make sure we are as well prepared as possible to help during the hackathon sessions could you please add/attach to this issue:

1. The landing page URL of any component/workflow you have registered
2. The OMTD-SHARE XML file for each component/workflow
3. One or two sample documents that you expect to produce sensible output for your component/workflow

**Comment by AlexJoom** [comment] 2018-04-16 13:40
Hi Mark, we have uploaded a new version at Maven taking into account your suggestions:
- META-INF/eu.openminted.share/descriptors.txt is now lowercased
- Our descriptors.txt is now automatically generated via the plugin.
- Our local UIMA CAS descriptors are located insite the org.apache.uima.fit folder. 

1) [Landing page url](https://services.openminted.eu/landingPage/component/f2660496-0662-4d12-b3f1-2cc65a7e5764)
2) [OMTD-share xml zipped](https://github.com/openminted/Open-Call-Discussions/files/1915458/vinesum-omtd-share.xml.zip)
3) 3 files that you can use in order to run an example.
[test1.txt](https://github.com/openminted/Open-Call-Discussions/files/1915451/test1.txt)
[test2.txt](https://github.com/openminted/Open-Call-Discussions/files/1915452/test2.txt)
[test3.txt](https://github.com/openminted/Open-Call-Discussions/files/1915453/test3.txt)

More information can be found at [page 3 - 6](https://docs.google.com/document/d/11DXM1GJEgzgdvE0_yafrfCjN7N6FUmZxsfBfU_Z45f0/edit?usp=sharing) where we describe the input and output.
In our example these are run using a org.apache.uima.fit.pipeline.SimplePipeline that just reads the text from these files.

Can you confirm that you have all the required information?
During the hackathon session we can also share screen and run the component via IntelliJ/Eclipse

Best,

**Comment by pennyl67** [comment] 2018-04-16 20:45
Hi
Just to confirm that the metadata record contains required/recommended information. 
A couple of improvements, though, that could be made to enhance the visibility and discoverability of the component (they're only suggestions and not imperative) are:
1) the addition of information on the annotation types that you extract in the description of the output resource. Taken from the OMTD-SHARE ontology, these are:
http://w3id.org/meta-share/omtd-share/Person
http://w3id.org/meta-share/omtd-share/Location
http://w3id.org/meta-share/omtd-share/Date
given that "vine variety" is not included in the ontology: use http://w3id.org/meta-share/omtd-share/AgriculturalEntity + add the element "annotationTypeOther" with the value "vineVariety"
2) information on the authority list you're using (i.e. the International list of vine varieties) in the componentDependenciesInfo under the element "annotationResource".
Best,
Penny

**Comment by pennyl67** [comment] 2018-04-16 20:47
Just a clarification: the previous comment concerns the metadata as a description and doesn't take into account any technical details, e.g. if you're using parameters.

**Comment by AlexJoom** [comment] 2018-04-18 11:37
Thanks for the support Penny! 

We would be happy to include your suggestions in future versions. To achieve this, we would need explicit examples of how these OMTD-Share ontologies are mapped to UIMA descriptors, and what would need to be included in the source code to take advantage of corresponding objects.
Let us keep this as a future TODO.

**Comment by pennyl67** [comment] 2018-04-18 12:21
Yes, I understand what you mean. Just keep in mind that if you upload the component as a private one (I think that's the default when coming from Maven; is this true @greenwoodma ?) you can always use the editor to modify/improve the metadata record. The editing facility can be found by clicking on "My components" under your account name at the top right of the page. 
Just remember that once a component is made public, the metadata record cannot be changed for reproducibility reasons.
But as I said, these are recommendations.

**Comment by greenwoodma** [comment] 2018-04-18 12:24
Yes I believe all components, including those pulled directly from maven, or private by default, and if they aren't then that's a bug not a feature!

**Comment by greenwoodma** [comment] 2018-04-18 12:37
I also just noticed @AlexJoom that the application has been registered on http://services.openminted.eu. Could you please re-register the latest version on https://test.openminted.eu/ -- it's actually more up to date than services and contains a number of bug fixes and performance improvements and it's where we are asking all open call participants to register their components/applications, at least for now.

**Comment by greenwoodma** [comment] 2018-04-18 12:41
okay, scratch that. Seems we are in the process of updating services so I'm not quite sure where we'll need things registering. Sorry. Will get back to you once we have a final decision.

**Comment by greenwoodma** [comment] 2018-04-18 12:56
okay for now if you could upload the latest version to test and let me know the landing page then I can start testing, and we can always move them to services later. Given the time constraints etc. this seems the best way forward for now. Sorry for the earlier confusion

**Comment by AlexJoom** [comment] 2018-04-18 14:43
No prob @greenwoodma 
The url is:
https://test.openminted.eu/landingPage/component/f2660496-0662-4d12-b3f1-2cc65a7e5764

**Comment by greenwoodma** [comment] 2018-04-19 15:36
Sorry to not have done this before but we could do with organising a time for a quick online chat (i.e. the hackathon). The original plan was to try and do that this week. Would you have time tomorrow to talk? I can currently do any time between 08:00BST and 16:00BST.

**Comment by AlexJoom** [comment] 2018-04-19 21:57
sure @greenwoodma 
14:00BST should be fine!
You can message me at hangouts (alexandros.tzoumas@gmail.com) or skype (alexandros.tzoumas@outlook.com)

**Comment by greenwoodma** [comment] 2018-04-20 06:57
Perfect. I'll probably use a hangout as I know I've had issues with skype versions recently.

**Comment by greenwoodma** [comment] 2018-04-20 10:39
Just a quick update... I've now created an application using your component and run it over the three sample files you provided (I had to convert them to PDF first so that they would fit the usual style of corpus). I've attached the resulting process corpus for you to look at. Unfortunately while it seems that the type system contains your Entity type definition, none of the processed files (in the output folder) seem to have any annotations. Can you spot anything odd that might have caused this in the files, before I try digging further?

[2f1c6501-bc83-49e8-98a5-d4d8802028e4.zip](https://github.com/openminted/Open-Call-Discussions/files/1931779/2f1c6501-bc83-49e8-98a5-d4d8802028e4.zip)

**Comment by greenwoodma** [comment] 2018-04-20 10:44
also these are the XMI files fed into your component after being converted from PDF by the platform, if that helps in debugging etc.

[5_ PdfReader_output.zip](https://github.com/openminted/Open-Call-Discussions/files/1931800/5_.PdfReader_output.zip)

**Comment by AlexJoom** [comment] 2018-04-20 13:02
@greenwoodma  i think i have an idea of what the problem may be.

Our [code](http://bitbucket.scify.org/projects/OP/repos/vinesum/browse/omtdvinesum/src/main/java/org/scify/vinesum/annotators/OmtdVineSumAnnotator.java)  expects to process an org.apache.uima.jcas.JCas object and read the text from method [jcas.getDocumentText](http://uima.apache.org/d/uimaj-2.8.1/apidocs/org/apache/uima/jcas/JCas.html#getDocumentText()) (line 43).

This works fine in our [example](http://bitbucket.scify.org/projects/OP/repos/vinesum/browse/omtdvinesum/src/main/java/org/scify/vinesum/example/VineSumExperiment.java) where we create a simple UIMA pipeline just to demonstrate how it works ( i believe the OpenMinted platform does this for us, creates pipelines with various components and executes them)

Having a look at the xmis we may have to use also [jcas.getSofaDataString()](http://uima.apache.org/d/uimaj-2.8.1/apidocs/org/apache/uima/jcas/JCas.html#getDocumentText) as a fallback

We can upload a new version so you can test it!


Let's also discuss it over the hangouts

**Comment by greenwoodma** [comment] 2018-04-20 17:14
Hi @AlexJoom my sincere apologies for having to cancel the call at the last minute this afternoon. I'm available the same times, 08:00BST to 16:00BST, on Monday if you are available.

As to the issue reading from the XMI documents I'm afraid I'm not really a UIMA expert (in fact I have almost no UIMA experience being a GATE developer). @reckart any ideas on the best way of reading the document string out of an XMI file.

**Comment by galanisd** [comment] 2018-04-20 17:51
Alexandros knows how to do it. Also I sent him a an example...we discussed the issue in Google hangouts ....

**Comment by greenwoodma** [comment] 2018-04-20 17:59
perfect, thanks @galanisd

**Comment by reckart** [comment] 2018-04-20 18:37
If you consider extracting the raw text directly from the XMI file, then look for 
an element "cas:Sofa" with the attribute "sofaID='_InitialView'" and fetch the
text from the attribute "sofaString".

For an example of a *very* simple XMI file where it is easy to see how the text is
stored, check out [1].

Doing this extraction directly from the XMI file is probably the simplest way. If you are in Java, you can make direct use of UIMA/uimaFIT to read the XMI file into memory and access its contents:

```
JCas jcas = JCasFactory.createJCasFromPath(pathToTypeSystemFile);
XmiCasDeserializer.deserialize(new FileInputStream(xmiFile), jcas.getCas();
jcas.getDocumentText();
```

[1] https://github.com/openminted/interop-examples/blob/master/example-output/plaintext_document.xmi

**Comment by AlexJoom** [comment] 2018-04-23 12:37
Hi @greenwoodma 

We uploaded a new version 
[Test landing page](https://test.openminted.eu/landingPage/component/ed48e424-2bbc-4b1f-8569-bf9eac9ae613)
[Production landing page](https://services.openminted.eu/landingPage/component/3464bf7f-08b2-4a7f-90b7-65030fdceb15)

Testing it with your input [5_.PdfReader_output.zip](https://github.com/openminted/Open-Call-Discussions/files/1938152/5_.PdfReader_output.zip) (the files you've send to us above)
We produce the following output [vinesum_output.zip](https://github.com/openminted/Open-Call-Discussions/files/1938155/vinesum_output.zip)

Can you check again?

@galanisd  we added to the project also an xmi reader to demonstrate it
[VineSumXmiExperiment](http://bitbucket.scify.org/projects/OP/repos/vinesum/browse/omtdvinesum/src/main/java/org/scify/vinesum/example/VineSumXmiExperiment.java)
```

public static void main(String[] args) throws UIMAException, IOException {
		runPipeline(
			createReaderDescription(
					XmiReader.class,
					XmiReader.PARAM_SOURCE_LOCATION, "resources/example/xmi",
					XmiReader.PARAM_LANGUAGE, "en",
					XmiReader.PARAM_PATTERNS, new String[] { "[+]*.xmi" }),
			createEngineDescription(OmtdVineSumAnnotator.class),
			createEngineDescription(XmiWriter.class,
					XmiWriter.PARAM_TARGET_LOCATION, "resources/example/xmi/output")
		);
	}


```

thanks for your support!

**Comment by greenwoodma** [comment] 2018-04-23 13:07
Hmmm, I'm still not getting sensible results. The output zip contains the XMI files and typesystem but I'm still not seeing anotations

[32e0d7f9-f579-4c18-beae-b7b6b1116bc1.zip](https://github.com/openminted/Open-Call-Discussions/files/1938282/32e0d7f9-f579-4c18-beae-b7b6b1116bc1.zip)

@galanisd I assume that the right version has ended up on the test executor (I removed some old wrappers from the editor that were stopping me from getting to the new version). Looking at the job output via the Galaxy API I can see this command being run

`Linux_runUIMA.sh org.scify_omtdvinesum_1.0.3 org.scify.vinesum.annotators.OmtdVineSumAnnotator -input tmp -output /srv/galaxy/database/jobs_directory/000/879/working/out/`

which would suggest to me we are getting 1.0.3 which @AlexJoom I believe is the latest version?

**Comment by galanisd** [comment] 2018-04-23 13:22
I opened vinesum_output.zip. 
Screenshot.

![3](https://user-images.githubusercontent.com/10739759/39129097-3a56aefa-4712-11e8-94a1-ed7b06961102.png)

I can see some VineSum annotations. But not sure if they are correct..
What exactly is the issue?

Also had a look in container logs ....Nothing weird there...

**Comment by AlexJoom** [comment] 2018-04-23 13:28
Hm @greenwoodma yes this is the version.

@galanisd  yes these are the types we have defined in our component. At @greenwoodma 's .zip file these are missing

**Comment by galanisd** [comment] 2018-04-23 13:38
I thought that the output that you sent was a result that you got from the platform.

**Comment by AlexJoom** [comment] 2018-04-23 13:41
no @galanisd  this what we procude, when we run an xmi pipeline [VineSumXmiExperiment](http://bitbucket.scify.org/projects/OP/repos/vinesum/browse/omtdvinesum/src/main/java/org/scify/vinesum/example/VineSumXmiExperiment.java) to demonstrate it

![image](https://user-images.githubusercontent.com/3759333/39130211-34de79b4-4715-11e8-9fbe-2f5c2c6f55ae.png)

**Comment by greenwoodma** [comment] 2018-04-23 13:44
So @AlexJoom just to confirm, in 1.0.3 you can read those XMI files and produce correct output with annotations?

If that's the case I wonder why it's not producing output on the platform given it seems to be using 1.0.3 from the command line I dug out of the Galaxy API. Very odd.

**Comment by galanisd** [comment] 2018-04-23 13:45
- The UIMA executor that we have does exactly the same with the code that you sent.
- I am creating an app right now to test.

**Comment by pennyl67** [comment] 2018-04-23 13:47
@AlexJoom I've had a look at your documentation and I got the feeling that it's actually two components, a NER and a clustering component; can I ask why you are not adding them as two separate components?

**Comment by AlexJoom** [comment] 2018-04-23 14:10
Hi Penny,
it's because our component does NER based clustering, thus with one process we extract two types of inter-dependent annotations.

**Comment by galanisd** [comment] 2018-04-23 15:29
I have just noticed in the log that 3 "null" messages are printed in UIMA executor. 
I assume one for each file that we have in the corpus.

In your annotator 
http://bitbucket.scify.org/projects/OP/repos/vinesum/browse/omtdvinesum/src/main/java/org/scify/vinesum/annotators/OmtdVineSumAnnotator.java

there is a
`else {
			System.out.println(api.getError());
		}`
which is executed when something in the analysis fails...

I did some tests in my laptop. I think that the "nulls' are coming from this line.
I assume that there is some dependency conflict between OMTD executor libraries and your libraries.

I am trying to find what goes wrong.

Dimitris

**Comment by galanisd** [comment] 2018-04-23 16:42
- It is a little bit hard to debug it because errors are hidden here.
http://bitbucket.scify.org/projects/OP/repos/vinesum/browse/vinesumcore/src/main/java/org/scify/vinesum/vinesumcore/extractors/VineSumAPI.java

- One solution for the issue is to dockerize  your component; it will make things much easier..
I can provide some help. It is just a dockerfile of few lines.

- Is it possible to talk in hangouts or skype tomorrow?
@greenwoodma @AlexJoom

**Comment by AlexJoom** [comment] 2018-04-24 08:13
Hi @galanisd , could it help if we allowed the exception to be thrown?

We could dockerize it yes, but we would like also to understand the effort, since we are having deadlines for other projects these weeks and we are under pressure.

Yes we will be available for skype/hangouts!

**Comment by greenwoodma** [comment] 2018-04-24 08:22
Yes I agree with @AlexJoom it would be nice to get this working properly without resorting to docker, as we need to fully support UIMA components long term anyway. I can chat any time today as long as we finish before 15:00BST

**Comment by AlexJoom** [comment] 2018-04-24 08:30
we are releasing a new version 1.0.4 to maven central that allows the exceptions to propagate instead of printing to console, to assist at debugging it. it may take 1-2 hours to become visible

**Comment by greenwoodma** [comment] 2018-04-24 08:34
perfect. If you could register that and then share the landing page URL that would be really helpful

**Comment by AlexJoom** [comment] 2018-04-24 11:44
We uploaded version 1.0.4
[Services landing page](https://services.openminted.eu/landingPage/component/9923c8bf-09fa-4156-b7fa-4a2b3e75d030)
[Test landing page](https://test.openminted.eu/landingPage/component/011c7f5d-b88e-44ba-8b27-c6e70b8181d1)

this one let's exceptions propagate

**Comment by galanisd** [comment] 2018-04-24 12:02
Please can we discuss the issue in one hour 14:00 BST -- 16:00 Greek time?

I will have a look in v.1.04 right now.

**Comment by AlexJoom** [comment] 2018-04-24 12:04
yes, i ll be on hangouts (alexandros.tzoumas@gmail.com) or skype ( alexandros.tzoumas@outlook.com)

**Comment by greenwoodma** [comment] 2018-04-24 12:05
yes, that works for me

**Comment by galanisd** [comment] 2018-04-24 12:45
Seems that the OpenNLP model is never loaded...Not sure.

```
Caused by: java.lang.NullPointerException: null
	at opennlp.tools.sentdetect.SentenceDetectorME.<init>(SentenceDetectorME.java:90) ~[opennlp-tools-1.5.3.jar!/:1.5.3]
	at org.scify.vinesum.vinesumcore.extractors.tools.OpenNLPSentenceSplitter.splitToSentences(OpenNLPSentenceSplitter.java:77) ~[vinesumcore-1.0.4.jar!/:na]
	at org.scify.vinesum.vinesumcore.extractors.VineSumAPI.analyse(VineSumAPI.java:51) ~[vinesumcore-1.0.4.jar!/:na]
	at org.scify.vinesum.annotators.OmtdVineSumAnnotator.process(OmtdVineSumAnnotator.java:46) ~[omtdvinesum-1.0.4.jar!/:na]
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-2.6.0.jar!/:2.6.0]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385) [uimaj-core-2.6.0.jar!/:2.6.0]
	... 19 common frames omitted

```

**Comment by galanisd** [comment] 2018-04-24 13:00
In one project ...I use something like this...
```
URI uri = VineSumAPI.class.getResource("path").toURI();
Paths.get(uri).toFile();
```

**Comment by reckart** [comment] 2018-04-24 13:19
Mind that resources retrieved from the classpath cannot be accessed as a file in most cases because the resource usually resides in a JAR file. Such code normally only works in the IDE. The general approach is to open the URI/URL as a stream.

**Comment by galanisd** [comment] 2018-04-24 13:26
This is correct..The example that I provided will probably not work outside an IDE. I will try to find something that does what we want.

**Comment by AlexJoom** [comment] 2018-04-26 11:31
Hi @greenwoodma  and @galanisd 

we've uploaded a new version at **Maven Central** and **succesfully tested via console** (resources are now read correcly with getResourceAsStream() method)

We have a problem making the component public at the **OMTD platform** ( "test" and "services" enviroments). Once this is resolved we can also provide the landing pages

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

The following are provided just for reference (in case you find it helpful)
We tested by running at following console command below (VineSumXmiExperiment class has a main method which runs a xmi uima pipeline)

Console command:
- The updated versions were downloaded by [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.scify%22)
  Files at the example below **/home/alex/Desktop/omtdvinesum-1.0.6.jar** and /**home/alex/Desktop/vinesumcore-1.0.5.jar**
- all the other dependencies are at my local artifactory /home/alex/.m2/repository/
- the input xmi documents are at folder /home/alex/Desktop/xmi
- the output xmi documents will be placed at folder /home/alex/Desktop/xmi/output

`
java -cp /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/home/alex/Projects/vinesum/omtdvinesum/target/omtdvinesum-1.0.5.jar:/home/alex/.m2/repository/org/apache/opennlp/opennlp-tools/1.5.3/opennlp-tools-1.5.3.jar:/home/alex/.m2/repository/org/apache/opennlp/opennlp-maxent/3.0.3/opennlp-maxent-3.0.3.jar:/home/alex/.m2/repository/net/sf/jwordnet/jwnl/1.3.3/jwnl-1.3.3.jar:/home/alex/.m2/repository/org/apache/opennlp/opennlp-uima/1.5.3/opennlp-uima-1.5.3.jar:/home/alex/.m2/repository/gr/demokritos/JInsect/1.1/JInsect-1.1.jar:/home/alex/.m2/repository/salvo/jesus/OpenJGraph/1.1/OpenJGraph-1.1.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.io.text-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.io.text-asl-1.6.2.jar:/home/alex/.m2/repository/org/apache/uima/uimaj-core/2.6.0/uimaj-core-2.6.0.jar:/home/alex/.m2/repository/org/apache/uima/uimafit-core/2.1.0/uimafit-core-2.1.0.jar:/home/alex/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar:/home/alex/.m2/repository/org/springframework/spring-core/3.1.2.RELEASE/spring-core-3.1.2.RELEASE.jar:/home/alex/.m2/repository/org/springframework/spring-asm/3.1.2.RELEASE/spring-asm-3.1.2.RELEASE.jar:/home/alex/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/home/alex/.m2/repository/org/springframework/spring-context/3.1.2.RELEASE/spring-context-3.1.2.RELEASE.jar:/home/alex/.m2/repository/org/springframework/spring-aop/3.1.2.RELEASE/spring-aop-3.1.2.RELEASE.jar:/home/alex/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/alex/.m2/repository/org/springframework/spring-expression/3.1.2.RELEASE/spring-expression-3.1.2.RELEASE.jar:/home/alex/.m2/repository/org/springframework/spring-beans/3.1.2.RELEASE/spring-beans-3.1.2.RELEASE.jar:/home/alex/.m2/repository/com/ibm/icu/icu4j/4.0.1/icu4j-4.0.1.jar:/home/alex/.m2/repository/commons-io/commons-io/2.0.1/commons-io-2.0.1.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.io-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.api.io-asl-1.6.2.jar:/home/alex/.m2/repository/org/apache/ant/ant/1.8.1/ant-1.8.1.jar:/home/alex/.m2/repository/org/apache/ant/ant-launcher/1.8.1/ant-launcher-1.8.1.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.metadata-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.api.metadata-asl-1.6.2.jar:/home/alex/.m2/repository/org/apache/uima/uimaj-document-annotation/2.6.0/uimaj-document-annotation-2.6.0.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.io.xmi-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.io.xmi-asl-1.6.2.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.resources-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.api.resources-asl-1.6.2.jar:/home/alex/.m2/repository/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar:/home/alex/.m2/repository/org/tukaani/xz/1.0/xz-1.0.jar:/home/alex/.m2/repository/org/apache/maven/maven-model/3.0.5/maven-model-3.0.5.jar:/home/alex/.m2/repository/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar:/home/alex/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.tokit-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.tokit-asl-1.6.2.jar:/home/alex/.m2/repository/commons-jxpath/commons-jxpath/1.3/commons-jxpath-1.3.jar:/home/alex/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl-1.6.2.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.6.2.jar:/home/alex/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.featurepath-asl/1.6.2/de.tudarmstadt.ukp.dkpro.core.api.featurepath-asl-1.6.2.jar:/home/alex/.m2/repository/eu/openminted/share/annotations/omtd-share-annotations-api/3.0.2.5/omtd-share-annotations-api-3.0.2.5.jar:/home/alex/Desktop/omtdvinesum-1.0.6.jar:/home/alex/Desktop/vinesumcore-1.0.5.jar org.scify.vinesum.example.VineSumXmiExperiment /home/alex/Desktop/xmi /home/alex/Desktop/xmi/output`

the expected output is the xmi files at the defined folder, additionally the following are also printed at the console.

> Apr 25, 2018 3:37:19 PM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase scan(384)
INFO: Scanning [file:/home/alex/Desktop/xmi/]
Apr 25, 2018 3:37:19 PM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase initialize(219)
INFO: Found [3] resources to be read
Found "Grechetto" which is a vine_variety
Found "Grechetto" which is a vine_variety
Found "Greco di Tufo" which is a vine_variety
Found wine cluster "283654536"
Found wine cluster "2100285929"
Found event cluster "Grechetto_1.0_Greco_1.0_2.0_Tufo_0_1.0_0_di_1.0_0_1.0_1.0_Grechetto_1.0_Greco_1.0_0_Tufo_0_0_0_di_1.0_1.0_0_0_"
Found "Central" which is a location
Found "Central" which is a location
Found "Grechetto" which is a vine_variety
Found "Grechetto" which is a vine_variety
Found "Greco" which is a vine_variety
Found "Greco" which is a vine_variety
Found "Greco" which is a vine_variety
Found "Italy" which is a location
Found "Greco b" which is a vine_variety
Found "Greco b" which is a vine_variety
Found wine cluster "1918623930"
Found wine cluster "2100285929"
Found wine cluster "1948307816"
Found event cluster "Central_3.0_Grechetto_3.0_3.0_Greco_2.0_3.0_0_Italy_1.0_2.0_0_0_b_1.0_1.0_2.0_0_0_Central_3.0_Grechetto_3.0_0_Greco_2.0_0_0_Italy_1.0_1.0_0_0_b_1.0_0_1.0_0_0_"
Found "Grechetto" which is a vine_variety
Found "Grechetto b" which is a vine_variety
Found "1989." which is a date
Found "Gamay" which is a vine_variety
Found "Trebbiano spoletino b" which is a vine_variety
Found wine cluster "-656315663"
Found wine cluster "2100285929"
Found wine cluster "-273635189"
Found wine cluster "384708963"
Found event cluster "1989_1.0_Gamay_1.0_1.0_Grechetto_1.0_0_0_Trebbiano_1.0_0_1.0_1.0_b_1.0_1.0_2.0_0_0_spoletino_1.0_0_1.0_0_1.0_0_1989_1.0_Gamay_1.0_0_Grechetto_1.0_0_1.0_Trebbiano_1.0_0_0_0_b_1.0_0_0_1.0_1.0_spoletino_1.0_1.0_0_0_0_0_"

Thanks a lot for your support!

**Comment by galanisd** [comment] 2018-04-26 12:37
- Tested version 1.0.6 locally in my laptop . 
It worked I think. Input&output attached. Please have a look.

[VineIN.zip](https://github.com/openminted/Open-Call-Discussions/files/1951103/VineIN.zip)
[VineOut.zip](https://github.com/openminted/Open-Call-Discussions/files/1951104/VineOut.zip)

- The same script is installed in the UIMA image that is used to start a container in our Galaxy/Mesos setup. So I expect to also work when you will run it from the platform.

- In the workflow editor you can see a VineSum component. It is the latest (1.0.6) even though in Registry is not public. (Bug to be fixed). So you can create a workflow there an app in Registry and test. 

- Have you uploaded a corpus which is a good test case?

**Comment by AlexJoom** [comment] 2018-04-26 12:51
yes the VineOut seems fine

we haven't uploaded a corpus since it was not in our plans to create one (and no related effort was described in our proposal). Though, we manually extracted the provided demo example files from Agris Fao online service.

Regarding the work flow editor, great, we'll have a look thanks!

**Comment by galanisd** [comment] 2018-04-26 12:59
Actually I had a workflow for your app. I replaced Vine component with the latest...saved an app to the Registry etc.

![vine](https://user-images.githubusercontent.com/10739759/39307000-5291f81c-496a-11e8-9898-6b9d35671cbe.png)

Then I fed the app with a corpus I found in the Registry...and the execution finished. So I think we are OK.

![vinesuccess](https://user-images.githubusercontent.com/10739759/39307145-b9460602-496a-11e8-8f74-62f12f9c9f99.png)

Unfortunately I was not able to make the workflow/app public so I can share it with you.

**Comment by pennyl67** [comment] 2018-04-26 18:40
@AlexJoom You can now proceed to the uploading of the final version at services.openminted.eu, which has been cleaned from all previous resources, so that we know that everything is updated. Should you run into any problems, please let us know.
Thanks!

**Comment by pennyl67** [comment] 2018-04-26 19:58
@AlexJoom My mistake, please refrain from uploading at services.openminted.eu until further notice.

**Comment by gkirtzou** [comment] 2018-05-09 12:07
Dear @AlexJoom  you can now proceed to the uploading of your component at https://services.openminted.eu/home

Just, some final suggestions, not obligatory but recommended, for the metadata record are
- Add in both input and output resource info the language(s) that your component can handle.
- Add the resourceCreator with contact yourself, for citation reasons.
- Add documentation to either user manuals or publication for citation reasons.

Please, when you upload your component, create the appropriate workflow so that someone could run your component using the workflow editor. For more info see https://openminted.github.io/releases/workflow-editor/
Please also let me know when you have uploaded the your component to the production site.
If you encounter any problems, please let us know.
Thanks

**Comment by gkirtzou** [comment] 2018-05-10 11:25
Note that when you create an application, you wiil be asked to fill in a metadata record. Some tips for filling it in - so that they are discoverable by the users but also that users can cite you and your resource. 
- Give the application a unique name that humans can read and short enough
- Give an explanatory description; remember you can re-use the description of the component(s) in the workflow accumulatively
-  Add in the inputProcessingResourceInfo the information of the first component used in the workflow (the one after omtdImpoter), and in the outputResourceInfo the information of the last component; if the annotations from previous components are retained in the final output, please add those as well
-  (optionally) You can use the relations set with the relation "hasPart" to document the components used in the workflow - it can be repeated multiple times.

**Comment by snikolakis** [comment] 2018-05-10 11:26
Hi @gkirtzou , we have uploaded our component here:
https://services.openminted.eu/landingPage/component/24d68cdd-1e24-47a6-8006-5f6d08718dc3

All the recommended fields for the metadata record have been filled and we created a new workflow here: https://services.openminted.eu/landingPage/application/7cc09c26-d310-43be-b753-ede278589fd6

Thank you.

**Comment by gkirtzou** [comment] 2018-05-10 12:06
@spyninja I can see the application but no the component (it is private). COuld you send me the metadata record in xml?

**Comment by gkirtzou** [comment] 2018-05-10 12:07
@spyninja  sorry the reverse. I can see the component but not the application.

**Comment by snikolakis** [comment] 2018-05-10 12:10
I'm sorry for the inconvenience, I have made the application public, as well.

**Comment by pennyl67** [comment] 2018-05-16 09:53
Closing the issue: application public in services and tested with Chebi corpus

**Closed as completed by pennyl67** 2018-05-16 09:53 UTC
Labels: UIMA, Component
